- devices.go
- examples/simple/cmd/main.go
- examples/simple/simpledriver.go
- profiles.go
- protocoldriver.go
- service.go
There are a number of gofmt errors that slipped through
when we did the initial code import.  This commits cleans
them all up.
Signed-off-by: Tony Espy <espy@canonical.com>
> [gofmt] Cleanup gofmt errors

- async.go
- command.go
- command_test.go
- commandresult_test.go
- control.go
- devices.go
- profiles.go
- protocoldriver.go
- service.go
- status.go
- update.go
Instead passing a pointer to the Service struct
around as a parameter, instead just use the package
global svc var to access the struct.
Signed-off-by: Tony Espy <espy@canonical.com>
> Use package global svc var

- service.go
The value descriptor client path used `v1Event` instead of `v1Valuedescriptor`
> Fix value descriptor client initialitzation

- command.go
- commandrequest.go
- examples/simple/simpledriver.go
- protocoldriver.go
- service.go
This change re-factors the way the command endpoint requests processing of a related set of ResourceOperations from a concrete type which implements the **ProtocolDriver** interface.  The original code was based on the Java SDK. Each **ResourceOperation** was a single call the the protocol layer. This has been changed instead such that all of the **ResourceOperations** are passed in a single **CommandRequest** slice.  The call now is also synchronous, and returns a slice of **CommandResults** (and an error).
The only change I didn't make, was to change the **ResourceOperation** and **ValueDescriptor** fields in CommandResult from pointers to structs, this would be consistent with **CommandRequest**. I think the original justification of using pointers was efficiency, however it seems that …
> Refactor handle operation

- command_test.go
Current test module failed during `make test` command. Current pull request do next:
Fix creation of mock Service instance with proper name
Fix mock device cache
Fix inconsistency in tests output
Signed-off-by: Andriy Popovych <popovych.andrey@gmail.com>
> Fix command test

- devices.go
- service.go
This commit provide deviceCacheInterface which should be implemented to
support all required operations due to https://github.com/edgexfoundry/device-sdk-go/issues/14.
Signed-off-by: Andriy Popovych <popovych.andrey@gmail.com>
> Add device cache interface

- examples/simple/cmd/main.go
Initialize the flag sets. Reference https://golang.org/pkg/flag/#pkg-variables.
> Fix fails to run with confdir flag confict

- async.go
- command.go
- command_test.go
- commandrequest.go
- commandresult.go
- commandresult_test.go
- config.go
- control.go
- devices.go
- devices_test.go
- examples/simple/cmd/main.go
- examples/simple/simpledriver.go
- profiles.go
- protocoldiscovery.go
- protocoldriver.go
- schedules.go
- service.go
- status.go
- update.go
- update_test.go
- utils.go
- utils_test.go
- watchers.go
This commit fixs leakage of copyright notices into generated godoc, the latest of which can be seen here:
https://godoc.org/github.com/edgexfoundry/device-sdk-go
Signed-off-by: Tony Espy <espy@canonical.com>
> Update file headers to fix godoc copyright leakage

- devices.go
Currently when a device is removed, device cache and the profile cache aren't updated correctly
> Fixed remove device bad behaviour

- profiles.go
> Fixed bug in getDeviceObjectByName(). DeviceObject always was empty

- glide.yaml
fix #44
The version numbers are consistent with the same ones in edgex-go
> Add versions to glide.yaml

- internal/handler/command.go
fix #92
Make the behavior consistent with async.go
> Put Assertion error msg to reading value if failed

- internal/cache/devices.go
- internal/common/utils.go
- internal/mock/mock_addressableclient.go
- internal/provision/schedules.go
- service.go
The data type of Addressable Id was bson, and
it has been changed to string
Please see the change in edgex-go#938
fix #146
> Replace Addressable Id data type to string

- service.go
Device Service Id was bson data type, and it has become
string according to the design change in edgex-go.
Modify its data type to string to meet edgex-go.
fix #152
> Fix the wrong Device Service Id data type

- .dockerignore
- docker/Dockerfile
Changes made:
- Ignore go.sum. Currently there is an issue with the way checksums are computed across patch versions of Go. We have observed that if a go.sum is generated from Go 1.11.2 it may not work with Go 1.11.5. Typically this is seen as a checksum mismatch error on specific modules (github.com/hashicorp/go-rootcerts for example). Until we can get some resolution on this, go.sum will be ignored.
- Changed the base image to be golang:1.11-alpine as was discussed in the DevOps WG call.
- Commented out APK repo pinning.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
> Use golang:1.11-alpine as the base image. Ingore go.sum for the moment.

- internal/controller/restrouter.go
Fix #178 
API handlers are executed in the order they are added if a match is found.
> Fix API /api/v1/device/all/{command} not work

- go.mod
Update to the latest go-mod-core-contracts as the logic that handles client NotFound errors is currently broken.
See issue #182 for details.
> Update to latest go-mod-core-contracts

- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/docker/configuration.toml
- example/driver/simpledriver.go
- go.mod
- internal/cache/devices.go
- internal/common/types.go
- internal/common/utils.go
- internal/config/loader.go
- internal/handler/callback.go
- internal/handler/command.go
- internal/mock/mock_deviceclient.go
- internal/provision/devices.go
- manageddevices.go
- pkg/models/protocoldriver.go
Addressable in Device data model is replaced by map[string]map[string]string (protocols and protocolProperty)
fix #188
> Replace Addressable with string map in Device

- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/docker/configuration.toml
- internal/clients/init.go
- internal/common/types.go
On validate that all dependant services are available use already existing params in configuration.tolm file
Service/ConnectRetries
Service/Timeout
Signed-off-by: difince <dianaa@vmware.com>
> Make wait/retry params configurable

- internal/handler/command.go
- internal/handler/command_test.go
Issue #123. 400 error is handled by the overriding application logic.
Signed-off-by: Brandon Forster <brandonforster@gmail.com>
> Created error return condition for wrong parameter name.

- internal/config/loader.go
Adds error check to resolve segfault.
Publishes absolute path indicating from where we are attempting to load configuration.toml.
> Address #230 device simple startup crash

- internal/handler/callback/device.go
- internal/handler/callback/general.go
- internal/handler/callback/profile.go
to prevent the file name is the same as package name,
separating the function to three different go files.
fix #237
> Refactor callback.go to different go files

- go.mod
- internal/common/utils.go
- service.go
#254 
These changes are all related to the fact that the models.Service struct type in the core-contracts module went away. It was a hold-over from an inheritance relationship in the Java codebase and nothing else was using it except for DeviceService. Most of the DeviceService properties were found on the Service type, and have been moved.
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Integrate Core-Contracts Changes from Model Validation Work

- internal/config/loader.go
the profile was removed from config path in #231,
so add it back to meet the behavior of edgex-go
fix #257
> Add start up option -profile back to config path

- example/cmd/device-simple/res/Simple-Driver.yaml
The original EdgeX device profile required an attribute ('property')
in a device profile ResourceOperation that was always set to 'value'.
As such, this attribute was removed from the model, but still exists
in the example device profile YAML.
Fixes issue #247
> Remove RO 'property=value' from example devprof

- async.go
- internal/common/utils.go
- internal/handler/command.go
Device names in the Readings are redundant,
because they are the same name in the Event.
fix #269
> Remove Device name in Readings when sending Event

- async.go
- internal/common/utils.go
- internal/handler/command.go
- internal/provision/profiles.go
- pkg/models/commandvalue.go
- pkg/models/commandvalue_test.go
The float value of reading was base64 encoding only.
This commit makes it configurable by PropertyValue.
fix #107
Add new fields when careating ValueDescriptor
>  Make float encoding according to PropertyValue 

- internal/handler/command.go
- internal/provision/devices.go
- manageddevices.go
- managedprofiles.go
- service.go
Log messages shouldn't dump entire objects,
but some of them dump the large object.
Replace the object with its name, and remove
unnecessary message.
fix #202
> Make log messages not dump entire objects

- example/cmd/device-simple/main.go
- version.go
The Version field will override when running the build command(make build)
Fix #288
> Load version number from VERSION file

- internal/controller/correlation/handler.go
- internal/controller/correlation/middleware.go
- internal/controller/restrouter.go
Fix #278 
```
...
level=INFO ts=2019-05-16T01:30:04.900013Z app=device-simple source=service.go:117 msg="*Service Start() called, name=device-simple, version=1.0.0"
level=INFO ts=2019-05-16T01:30:04.900169Z app=device-simple source=service.go:123 msg="Listening on port: 49990"
level=INFO ts=2019-05-16T01:30:04.900342Z app=device-simple source=service.go:124 msg="Service started in: 30.4246ms"
level=DEBUG ts=2019-05-16T01:30:04.900487Z app=device-simple source=service.go:126 msg="*Service Start() exit"
level=TRACE ts=2019-05-16T01:30:06.925118Z app=device-simple source=middleware.go:40 correlation-id=121f95a6-610f-4605-a1a8-03fc24c7f919 path=/api/v1/ping msg="Begin request"
level=TRACE ts=2019-05-16T01:30:06.925507Z app=device-simple source=middleware.go:31 …
```
> Add correlation-id for API tracing

- go.mod
- internal/mock/mock_eventclient.go
Updates modules Go Codec to v1.1.4 and go-mod-core-contracts to latest.
Updates mock EventClient from go-mod-core-contracts which now has MarkPushedByChecksum method.
Signed-off-by: tobiasmo1 <tobias.mosby@intel.com>
> Update to Go Codec module v1.1.4

- example/driver/simpledriver.go
- pkg/models/protocoldriver.go
Remove DisconnectDevice for now, and will re-design the whole add, update, delete callback methods to meet the discovery mechanism in next release
fix #286
> Remove DisconnectDevice from ProtocolDriver

- .gitignore
- Makefile
- internal/common/utils.go
- internal/controller/restfuncs.go
- internal/handler/command.go
- pkg/models/event.go
Update to add the EventClient.MarshalEvent to encode CBOR and JSON events as byte array.
Send events to Core Data using EventClient.AddBytes method.
> Send CBOR/JSON events using contract EventClient

- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/docker/configuration.toml
This extends the device-simple example, updating the AutoEvents configuration to trigger a simple JSON and CBOR event for the `Simple-Device01` device.
AutoEvent now triggers `Image` command. This allows a manual PUT using curl or Postman to the `Switch` command, toggling SwitchButton value to true or false. This demonstrates how the subsequent events emitted from both `Switch` (JSON) and `Image `(CBOR) reflect the updated device state.
Ref issue #285
> Update Device-Simple example

- internal/cache/profiles.go
- internal/controller/restfuncs.go
- internal/provision/profiles.go
The $package and $func in log messages are unnecessary because of the current logger prints out the file name and line number.
Fix #76
> Remove redundant messages from log

- internal/transformer/transformresult.go
- internal/transformer/transformresult_test.go
Implement bitwise operations. Mask is used for cleaning the bits. Shift is used for shifting right or left.
Fix #281
> Implement mask and shift transforms

- example/cmd/device-simple/Dockerfile
- internal/common/consts.go
- internal/config/loader.go
- pkg/startup/bootstrap.go
- service.go
Use command line option to set the registry url
To meet the behavior of C SDK and make users more easy to set up the registry, we suggest to make -r or --registry to input the path string instead of a simple boolean:
-r, --registry=[URL]
parse URL as [type]://[location]
eg, consul://localhost:8500
fix #253
> Use command line option to set the registry url

- go.mod
Fix #300
In preparation for cutting the edinburgh branch, we need to consume
v0.1.0 in the go.mod for edgex modules
- go-mod-core-contracts
- go-mod-registry
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Update edgex modules to v0.1.0 pre-edinburgh

- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/docker/configuration.toml
- internal/common/types.go
- internal/config/test/configuration.toml
ReadMaxLimit should be controlled by Core services, and we don't really use it in SDK
fix #303
> Remove ReadMaxLimit from configuration

- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/docker/configuration.toml
- internal/common/types.go
- internal/config/test/configuration.toml
ReadMaxLimit should be controlled by Core services, and we don't really use it in SDK
fix #303
> Remove ReadMaxLimit from configuration in Edinburgh release

- async.go
- example/driver/simpledriver.go
- internal/autoevent/executor.go
- internal/common/utils.go
- internal/handler/command.go
- internal/mock/mock_devicevirtualdriver.go
- pkg/models/commandvalue_test.go
Use nanoseconds for all the Even, Reading, and Command Value in SDK
fix #273
> Adopt nanoseconds in origin of Event and Reading

- async.go
- internal/autoevent/executor.go
- internal/common/utils.go
- internal/common/utils_test.go
- internal/handler/command.go
Cache the previous timestamp, and plus 1 nanosecond if the new one
is not greater than the previous one
fix #314
> Make sure all the event.origin are unique

- internal/config/environment.go
- internal/config/environment_test.go
- internal/config/loader.go
- internal/config/loader_test.go
Added ability to override command-line provided useRegistry url with
environment variables -- edgex_registry_host, edgex_registry_port, and
edgex_registry_type to be consistent with edgex-go core implementation
(see https://github.com/edgexfoundry/edgex-go/issues/1450).
Added ability to override any configuration value with environment
variables for the use case where a command line registry value is
provided, the referenced registry does not have configuration for this
service, and this service pushes a copy of its local configuration into
the registry. The key in an environment variable specifies the
configuration value to override; e.g. Clients_Logging_Host=<someNewValue>
https://github.com/edgexfoundry/device-sdk-go/issues/323
Signed-off-by: Michael W. Estrin <me@michaelestrin.com>
> Override Configuration Using Environment Variables

- .gitignore
- snap/hooks/install
- snap/snapcraft.yaml
* Add basic snap of device-simple that uses a daemon to launch device-simple and uses consul
* Ignore snap files
This is not meant to be published by the project in the snap store, rather just serve as an example and to be used in the documentation for building device service snaps.
To test, [install support for snaps](https://docs.snapcraft.io/installing-snapd) on your Linux distro, and then install snapcraft with:
```bash
$ sudo snap install snapcraft --classic
```
Then build the snap by cd'ing to the directory where you have this branch checked out and run `snapcraft`:
```
$ cd $GOPATH/src/github.com/edgexfoundry/device-sdk-go
$ snapcraft
```
You may be prompted to install [multipass](https://multipass.run/), if you don't want to use multipass you can also use LXD.
After that you …
> Add example snap for building device-simple

- example/driver/simpledriver.go
- pkg/startup/bootstrap.go
Use async call to start the service and listen to the OS signal in bootstrap.
fix #242
> Listen to the OS signal during service startup

- .gitignore
- internal/autoevent/executor.go
- internal/common/consts.go
- internal/controller/restfuncs.go
- internal/handler/command.go
- internal/handler/command_test.go
This is an example/POC of the second 1/2 from PR:  https://github.com/edgexfoundry/edgex-go/pull/1571 to address issue: https://github.com/edgexfoundry/edgex-go/issues/1564. 
In summary, we place the query params into the Attributes with a key of "query" so as to not create a breaking change to support this. For example if `test=test&test2=test2` came from a GET Command, then those would be put into Attributes like so: `Attributes["query"]  = "test=test&test2=test2"`.
Certainly we could break each param out into a separate attribute, this PR is just meant to get the discussion going on ways to accomplish this.
> feature(query-params): Handle QueryParams from EdgeX Command Service

- internal/handler/command.go
This PR initializes attributes if it is not set in order avoid a panic.
Closes #343 
Signed-off-by: Mike Johanson <michael.johanson@intel.com>
> fix(query-params): Fix panic if attributes isn't initalized

- example/driver/simpledriver.go
- internal/config/environment_test.go
- internal/handler/callback/device.go
- internal/mock/mock_devicevirtualdriver.go
- pkg/models/protocoldriver.go
Add the following callbacks into ProtocolDriver interface:
AddDevice, UpdateDevice, and RemoveDevice
Modify device-simple to fit the interface change
Modify DriverMock to fit the interface change
Invoke the driver callbacks when Device Service callback and Provision
is executed
fix https://github.com/edgexfoundry/device-sdk-go/issues/276
> Add CUD callbacks into ProtocolDriver

- internal/provision/devices.go
- manageddevices.go
Since we have implemented Device callback to handle the CRUD
of Device cache, the redundant calls in provision/device.go
and manageddevices.go could be removed.
fix https://github.com/edgexfoundry/device-sdk-go/issues/317
> Remove the additional calls for Device cache

- go.mod
- internal/common/consts.go
- internal/controller/restfuncs.go
- internal/controller/restrouter.go
- internal/handler/version.go
- internal/mock/mock_valuedescriptorclient.go
Add /version API to return version number to be consistent with other edgex services
Fix the http method filter in router 
fix #347
>  Add /version API

- internal/transformer/transformresult.go
- internal/transformer/transformresult_test.go
Base should the first parameter of math.Pow func. The original code is
wrong.  Also fix the unit test.
fix https://github.com/edgexfoundry/device-sdk-go/issues/359
> Fix the wrong transformation for base

- internal/config/loader.go
go-mod-registry will assign the service name into the config path, so
device-sdk doesn't need to do it
fix https://github.com/edgexfoundry/device-sdk-go/issues/350
> Remove the duplicated service name in config stem

- internal/transformer/transformvaluechecker.go
transformer.checkTransformedValueInRange limited Float32 and Float64
type cannot be zero value, but it should be valid.
fix https://github.com/edgexfoundry/device-sdk-go/issues/358
> Make 0 is valid for Float32 and Float64 reading

- example/cmd/device-simple/res/Simple-Driver.yaml
- internal/handler/command.go
- internal/handler/command_test.go
- internal/mock/data/deviceprofile/New-Device.json
- internal/mock/data/deviceprofile/Random-Boolean-Generator.json
- internal/mock/data/deviceprofile/Random-Float-Generator.json
- internal/mock/data/deviceprofile/Random-Integer-Generator.json
- internal/mock/data/deviceprofile/Random-UnsignedInteger-Generator.json
When performing a SET / PUT to a device resource, the value passed to the driver should be:
1. Parsed out of the JSON payload, otherwise
2. If this is part of a deviceCommand, the value of "parameter" in the resource operation, otherwise
3. The value of "defaultValue" in the deviceResource
If none of these are available, the operation fails (http 400)
fix https://github.com/edgexfoundry/device-sdk-go/issues/356
Since the implementation has become based on ResourceOperation loop, not parameters loop, the RO slice doesn't need to convert to map anymore
command_test.go needs to be refactored, so remove it for now
Related issue opened: https://github.com/edgexfoundry/device-sdk-go/issues/361
> Implement default values for parameters to SET cmd

- internal/controller/restfuncs_test.go
- internal/controller/restrouter.go
- internal/controller/restrouter_test.go
- service.go
Some device services (new rest DS) need to have their own REST endpoints. Currently these services have to run a second webserver and configure a separate port. This is not desirable. Adding an API which adds endpoint to existing webservice would make this much cleaner and removes need to specify a second port for the service.
closes #373
> feat(server): Add API to allow adding additional routes to internal Webserver

- internal/cache/devices.go
- internal/cache/profiles.go
- internal/cache/valuedescriptors.go
Add sync.mutex.Lock and Unlock to each operation in cache
Extract logic to private method to prevent deadlock
fix https://github.com/edgexfoundry/device-sdk-go/issues/366
> Add lock into cache to make sure the thread safety

- go.mod
- internal/endpoint/endpoint.go
- service.go
Fix #372
* ErrServiceClient is no longer a pointer
* Added min-supported Go version to go.mod (1.12 currently)
* Added Fetch() implementation to local Endpointer implementation
Signed-off-by: Trevor Conn <trevor_conn@dell.com>
> Update core-contracts reference to v0.1.30

- async.go
- example/cmd/device-simple/res/Simple-Driver.yaml
- go.mod
- internal/cache/profiles.go
- internal/cache/profiles_test.go
- internal/common/utils.go
- internal/handler/command.go
- internal/mock/data/deviceprofile/New-Device.json
- internal/mock/data/deviceprofile/Random-Boolean-Generator.json
- internal/mock/data/deviceprofile/Random-Float-Generator.json
- internal/mock/data/deviceprofile/Random-Integer-Generator.json
- internal/mock/data/deviceprofile/Random-UnsignedInteger-Generator.json
- internal/mock/mock_devicevirtualdriver.go
- internal/mock/mock_valuedescriptorclient.go
- internal/provision/profiles.go
- internal/transformer/transformresult_test.go
- managedprofiles.go
- service.go
Rename ResourceOperation.Object -> ResourceOperation.DeviceResource
Rename ResourceOperation.Resource -> ResourceOperation.DeviceCommand
upgrade go-mod-core-contracts from v0.1.30 to v0.1.31
Fix https://github.com/edgexfoundry/device-sdk-go/issues/245
> Rename fields within ResourceOperation

- service.go
Provision will cause the callback sent by Core Metadata, and sometimes
the protocol driver hasn't been ready.  Thus, the protocol driver
initialization should be run before Provision.
Fix https://github.com/edgexfoundry/device-sdk-go/issues/376
> Move protocol driver init before provision

- internal/clients/init.go
- internal/common/globalvars.go
- internal/provision/profiles.go
The Core Metadata GeneralClient should be the global variable like
other clients, so it could be reused without creating it each time.
If using Registry, each client creation will cause a new go routine to
run endpoint.Monitor(), so it has to be avoided.
Fix https://github.com/edgexfoundry/device-sdk-go/issues/388
> Move Metadata GeneralClient to global variable

- go.mod
- internal/common/consts.go
- internal/config/loader.go
- pkg/startup/bootstrap.go
Use [go-flags](https://github.com/jessevdk/go-flags) package to parse command line argument and implement following behaviors:
--registry=\<url\> - Use the registry at that url
--registry - Load the url from configuration.toml
\<no flag\> - Don't use the registry
`go-flags` allow us to set an `optional-value` when the option occurs without an argument. Currently the value is hard-coded as `LOAD_FROM_FILE` for readability.
Fix #253
> Update the --registry command line options

- Attribution.txt
- internal/config/loader.go
move call to `OverrideUseRegistryFromEnvironment` before all the comparisons of `useRegistry`  ,
also add `go-flags` package into `Attribution.txt`
Fix #401
> Override useRegistry from environment before related comparison

- Attribution.txt
- go.mod
- internal/autoevent/executor.go
- internal/autoevent/executor_test.go
Calculate and cache checksum using [xxHash](http://cyan4973.github.io/xxHash/) on binary readings to determine whether it changed since last autoevents.
Fix #261
> Add Binary Support for OnChange Autoevents

- internal/common/consts.go
- internal/common/utils.go
- internal/common/utils_test.go
- internal/handler/command.go
Use `regexp` package to filter out parameters with `ds-` prefix
We could use `Regexp.FindAllString` to handle those parameters in the future .
Fix #354
> Filter out query parameters with prefix "ds-" to ProtocolDriver

- internal/common/globalvars.go
- internal/config/loader.go
- pkg/startup/bootstrap.go
- service.go
Add -o and --overwrite flag to indicate whether the service should reload the configuration from local file to override the one on registry
Fix #342 
Alternative implementation of PR #348
> Add option to overwrite registry with local config

- RELEASE-NOTES.txt
Update RELEASE-NOTE for fuji branch to meet the change in v1.1.1
Fix https://github.com/edgexfoundry/device-sdk-go/issues/410
> Update RELEASE-NOTE for v1.1.1

- example/cmd/device-simple/res/configuration.toml
- internal/common/types.go
- internal/common/utils.go
Add a new setting `UpdateLastConnected` in device service's configuration, default is `false`.
If enabled, device's `LastConnected` attribute would be updated every time an event being sent to coredata.
Fix #371
> Add configurable option to update lastConnected attribute

- go.mod
- internal/endpoint/endpoint.go
go-mod-core-contracts has fix for YAML marshaling of PropertyValue.MediaType needed for using MediaType in YAML device profiles.
Latest go-mod-core-contracts also has change to Endpointer interface requiring changes to endpoint.go
Closes #424
> bug(MediaType): Update to latest go-mod-core-contracts for PropertyValue.MediaType fix

- go.mod
- internal/endpoint/endpoint.go
Fix on Fuji branch
go-mod-contracts has fix for YAML marshaling of PropertyValue.MediaType needed for using MediaType in YAML device profiles.
Latest go-mod-contracts requires update to endpoint.go
closes #427
> bug(MediaType): Fuji - Update to latest go-mod-contracts for PropertyValue.MediaType fix

- Makefile
- internal/autoevent/executor_test.go
Add another test in `make test` to make sure every file are formatted correctly.  (right now `make test` only list them so they're ignored very often. )
Fix #250 
> Add gofmt test in Makefile

- async.go
- example/driver/simpledriver.go
- internal/cache/profiles.go
- internal/cache/profiles_test.go
- internal/handler/command.go
Improve `CommandExists` logic to check the cmd exists in either deviceCommands or coreCommands, also remove resourceOperation requirement while transforming `CommandValue` to `Event` so that deviceResource can be accessed directly without definition of deviceCommands in device profile.
Fix #419,  #426
> Make deviceResource can be accessed directly

- Dockerfile.build
- Jenkinsfile
- example/cmd/device-simple/Dockerfile
- go.mod
- snap/snapcraft.yaml
Fix #440 
- As with other similar `PR`s addressing the upgrade to `Go 1.13`, after making the updates to the relevant files, I ensured that the Docker image got built and tagged.
> Update relevant files in device-sdk-go for Go 1.13. Closes #440.

- internal/handler/callback/general.go
- internal/handler/callback/provisionwatcher.go
- manageddevices.go
- managedwatchers.go
Add provisionwatcher callback handler, remove cache operation in `managedwatchers.go` to avoid duplicate operation in device service cache.
Fix #449
> Add provisionwatcher callback handler

- pkg/models/commandvalue.go
- pkg/models/commandvalue_test.go
Fix #457 
SDK encodes the float as base64 string by **big-endian** binary.
SDK encodes the float as base64 string by **little-endian** binary.
DS SDK spec:
> When EdgeX is given (or returns) a float32 or float64 value as a string, the format of the string is by default a base64 encoded little-endian of the float32 or float64 value
https://docs.google.com/document/d/1aMIQ0kb46VE5eeCpDlaTg8PP29-DBSBTlgeWrv6LuYk/edit
> Encode the float as base64 string by little-endian binary

- pkg/models/commandvalue.go
- pkg/models/commandvalue_test.go
Reverts edgexfoundry/device-sdk-go#458
This change breaks the backward compatibility, so revert it.
> Revert "Encode the float as base64 string by little-endian binary"

- internal/common/utils.go
- internal/handler/command.go
Extract the logic to a function for better maintainability also followed the discussion of #371 and #414, move the logic to PUT command as well. In the future if coredata were responsible for the update we can easily make the change.
> Add update-lastConnected logic to PUT command

- go.mod
- internal/cache/devices_test.go
- internal/cache/init.go
- internal/cache/init_test.go
- internal/cache/provisionwatchers_test.go
- internal/clients/init.go
- internal/common/utils.go
- internal/endpoint/endpoint.go
- internal/handler/callback/device.go
- internal/handler/callback/profile.go
- internal/handler/callback/provisionwatcher.go
- internal/handler/command_test.go
- internal/mock/mock_deviceclient.go
- internal/mock/mock_deviceprofileclient.go
- internal/mock/mock_eventclient.go
- internal/mock/mock_provisionwatcherclient.go
- internal/mock/mock_valuedescriptorclient.go
- internal/provision/devices.go
- internal/provision/profiles.go
- internal/transformer/transformresult.go
- internal/urlclient/factory.go
- pkg/service/init.go
- pkg/service/manageddevices.go
- pkg/service/managedprofiles.go
- pkg/service/managedwatchers.go
- pkg/service/service.go
Fixes #446 
Fixes #445
Signed-off-by: Brandon Forster <me@brandonforster.com>
> Refactored usage of service clients to be compatible with latest contracts changes.

- example/cmd/device-simple/Attribution.txt
- go.mod
- pkg/models/commandvalue_test.go
> Switch CBOR library for security

- pkg/service/init.go
- pkg/service/main.go
Refactor to start http server before SDK specific bootstrap and update BootstrapHandler.
Fix #491 
> Refactor bootstrap process

- example/README.md
- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/provisionwatcher.json
- example/driver/simpledriver.go
- internal/autodiscovery/autodiscovery.go
- internal/common/globalvars.go
- internal/common/types.go
- internal/controller/restfuncs.go
- internal/handler/control.go
- internal/mock/mock_devicevirtualdriver.go
- pkg/models/protocoldiscovery.go
- pkg/models/protocoldriver.go
- pkg/service/async.go
- pkg/service/init.go
- pkg/service/main.go
- pkg/service/service.go
- pkg/startup/bootstrap.go
Implement discovery via provisionwatcher following the [new design](https://github.com/edgexfoundry/edgex-docs/blob/8d0715376fd4fb63bebf1a891f5c25e4ffff7e06/design/legacy-design/device-service/discovery.md) .
Fix #418 
(PS: the provisionwatcher callback mechanism will be separated to another PR #450  )
> Implement dynamic device discovery

- example/cmd/device-simple/res/configuration.toml
- go.mod
- internal/common/types.go
Add the ServerBindAddr setting used for ListenAndServe in
go-mod-bootstrap, also update the ServiceInfo struct to include
this new field and remove the unused ClientMonitor to be consistent
with the ServiceInfo struct defined in go-mod-bootstrap
Fix #548 
> Add ServerBindAddr setting in configuration

- example/cmd/device-simple/res/configuration.toml
- go.mod
- internal/clients/init.go
- internal/common/config.go
- internal/common/types.go
- pkg/service/init.go
- pkg/service/main.go
remove the ConnectRetries configuration and use the startup
duration/interval instead and update the associated retry loops
during bootstrap process.
fix #561 
> fix: allow startup duration/interval to be overridden via env vars

- internal/clients/init.go
- pkg/service/init.go
go-mod-bootstrap translate SIGTERM to call cancel function to gracefully
stop long-running goroutine in SDK.
Add the exact behavior on goroutines that check dependency servicess and
refactor the package to be prepare for future removing global vars refactor.
fix #495
> fix: pass ctx into client initialization function

- internal/clients/clients.go
- internal/clients/init.go
- internal/clients/init_test.go
- internal/container/client.go
- internal/container/deviceservice.go
- pkg/service/async.go
- pkg/service/init.go
- pkg/service/main.go
- pkg/service/manageddevices.go
- pkg/service/managedprofiles.go
- pkg/service/managedwatchers.go
- pkg/service/service.go
The first part of removing global vars refactor.
Refactor the clients package to a BootstrapHandler to inject various
clients into dic, which will be pass all over SDK in the future refactor.
Expand and rename the Service struct to DeviceServiceSDK(refer to
app-function-sdk) to avoid using global vars in service package.
> refactor service and clients package

- example/cmd/device-simple/res/configuration.toml
- pkg/service/async.go
The asyncBufferSize not work as expected, all the async value wait in the same queue.
Issue Number: #552 
To enhance performance, refactor function to create a buffer and use goroutine for sending each AsyncValues.
> fix: Create a buffer to handle the AsyncValues

- internal/autodiscovery/autodiscovery.go
- internal/container/deviceservice.go
fix panic caused by not implementing ProtocolDiscovery and
add missing judgement to not start autodiscovery if disabled
in configuration
this is one of the issue found in https://github.com/edgexfoundry/device-virtual-go/pull/131
> fix: fix device autodiscovery behavior

- internal/autoevent/manager.go
- pkg/service/init.go
- pkg/service/main.go
Device Service callback API relies on autoevent manager to restart
autoevent for specific device, hence the manager need to at least
be initialized before the callback happening.
Revert the changes of making autoevent a BootstrapHandler and put
the logic back into DeviceService BootstrapHandler.
this fix the first issue found in https://github.com/edgexfoundry/device-virtual-go/pull/131#issuecomment-694615752
> fix: fix autoevent panic during callback

- openapi/v2/device-sdk.yaml
fix https://github.com/edgexfoundry/device-sdk-go/issues/555
Issue Number:
#555 
update v2 swagger callback API status code from 200 to 204, add 404 for PUT request, and change 400 to 404 for DELETE request
no
no
> Update V2 Swagger file callback API status code

- go.mod
- pkg/service/async.go
Update whitelist logic to make the new device be accepted if any of its
protocol match one of provisionwatcher's identifier.
Improve the adding discovered device logic to loop through all the PWs and
correctly break out if the device is successfully added.
fix #598
fix #606
> fix: improve device discovery flow and whitelist logic

- internal/autodiscovery/autodiscovery.go
- internal/autodiscovery/discovery.go
- internal/controller/restfuncs.go
- internal/handler/control.go
- internal/v2/controller/http/discovery.go
- pkg/service/async.go
Add a wrapper function to call discovery.Discovery() and release the
lock when call completed so that developer will not be forced to push
something to deviceCh to release the lock
Issue Number:
fix #609
> refactor(sdk): release lock after discovery complete

- pkg/service/service.go
registryClient was already available on DeviceService, just made it public
Signed-off-by: Alex Ullrich <alexullrich@technotects.com>
registryClient is available but not exported
Issue Number:
#621 
RegistryClient is available and exported
> feat(sdk): expose RegistryClient

- internal/v2/cache/devices.go
- internal/v2/cache/init.go
- internal/v2/cache/profiles.go
- pkg/service/init.go
the implementation is almost identical to v1cache except updating the
models to v2models. Also update the return error to edgexErr.Edgex type
for better trace/debug in the future.
note that the provisionwatcher and valuedscriptor are not yet ready in
core-contracts so we skip their corresponding cache.
> feat(sdk): prepare v2 cache for v2 callback api

- internal/autodiscovery/autodiscovery.go
- internal/autodiscovery/discovery.go
- pkg/service/async.go
- pkg/service/init.go
trigger auto-discovery on service startup, make the following changes
to avoid potential panic:
- remove closing channel call in receiver to avoid panic caused by driver
sending discovered device to closed channel.
- update deviceCh to be unbuffered so that the auto-discovery goroutine
won't be blocked
Issue Number: fix #547
> feat(sdk): start auto-discovery upon service startup

- internal/autoevent/executor.go
- internal/autoevent/executor_test.go
- internal/autoevent/manager.go
add check in StartAutoEvents function to avoid creating duplicate
autoevent executor and do some refactoring on autoevent package to
make it more readable
fix #596 
> fix(sdk): prevent creating duplicate autoevent executor

- internal/autoevent/executor.go
- internal/controller/restfuncs.go
- internal/handler/callback/general.go
- internal/handler/callback/service.go
fix #651 
DeviceService AdminState would be successfully updated by callback handler and autoevents would stop executing on Locked AdminState.
Also remove the AdminState check for callback api route so that DeviceService will keep syncing with metadata even if it's in Locked state. (otherwise DeviceService will not be able to unlock once it's locked)
> feat: add v1 deviceService callback handler

- example/cmd/device-simple/Attribution.txt
- go.mod
- internal/handler/command.go
- internal/handler/command_test.go
- internal/mock/consts.go
- internal/mock/data/deviceprofile/Random-Float-Generator.json
- internal/mock/mock_devicevirtualdriver.go
- internal/transformer/checkNaN.go
- internal/transformer/checkNaN_test.go
- internal/transformer/transformresult.go
- internal/transformer/transformresult_test.go
- internal/v2/application/command.go
- pkg/service/async.go
Fix #685 
When SDK throws overflow or NaN error, the other correct readings will be dropped. But the user still wants to receive the correct readings, so we need to set the reading value with overflow or NaN constant instead of the real error.
> feat: Make the numeric value type allows overflow and NaN

- internal/autoevent/manager.go
- pkg/service/init.go
- pkg/service/managedautoevents.go
When an auto discovery is used to find attached devices, there is no
easy way to attach an auto event to a newly discovered device.
Proposed new SDK APIs solve that problem. They can be used to add or
remove auto events from devices, from the Device Service context.
Resolves: #647
Signed-off-by: Tzvetomir Stoyanov (VMware)  <tz.stoyanov@gmail.com>
> feat(sdk): Implement Device AutoEvents SDK APIs

- example/cmd/device-simple/res/configuration.toml
- internal/common/config.go
- openapi/v1/device-sdk.yaml
Remote/file logging feature still available
Remote/file logging feature has been removed
> feat: Removed remote/file logging feature

- example/cmd/device-simple/Attribution.txt
- example/cmd/device-simple/res/configuration.toml
- go.mod
- internal/autoevent/executor_test.go
- internal/cache/init_test.go
- internal/clients/init_test.go
- internal/common/config.go
- internal/common/types.go
- internal/common/utils_test.go
- internal/controller/restfuncs_test.go
- internal/controller/restrouter_test.go
- internal/handler/command_test.go
- internal/transformer/transformresult_test.go
- internal/v2/application/command.go
- pkg/service/main.go
- pkg/service/service.go
Added creation and initialization SecretProvider during bootstrap for both secure and non-secure modes
Added InsecureSecrets and SecretStore config to device-simple as samples and used to test initializing SecretProvider in secure mode.
APIs to take advantage of the SecretProvider  are TBD in future PRs
This PR is about just about creating and initializing the Secret Provider. Using it come in following PR.
**Do the following to test this PR:**
- clone latest developer scripts repo
- Modify …
> feat: SecretProvider for storing/retrieving secrets

- pkg/service/main.go
- pkg/startup/bootstrap.go
Cleanup unused function parameters which had been converted to use the blank identifier.
- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)
This change doesn't impact the behavior of services based on the SDK.
NA
See issue description for more details.
> fix: rm unused pkg/service function params

- example/cmd/device-simple/Attribution.txt
- go.mod
- internal/common/consts.go
- internal/controller/restrouter.go
- internal/v2/controller/http/common.go
- internal/v2/controller/http/common_test.go
- internal/v2/controller/http/controller.go
- openapi/v2/device-sdk.yaml
No way to store secrets for the instance of a device service 
/api/v2/secret endpoint add to store exclusive secrets for the running device service instance.
This PR is dependent on PR https://github.com/edgexfoundry/device-sdk-go/pull/707
> feat: Add /api/v2/secret endpoint to store a secret

- internal/common/utils.go
- internal/handler/command.go
- internal/handler/command_test.go
- internal/transformer/checkNaN.go
- internal/transformer/transformparam.go
- internal/transformer/transformresult.go
- internal/transformer/transformresult_test.go
- internal/v2/application/command.go
- pkg/models/commandrequest.go
- pkg/models/commandvalue.go
- pkg/models/commandvalue_test.go
use the string ValueType defined in core-contracts to avoid duplicate
and for easier usage.
The `Type` field of `CommandValue` and `CommandRequest` models are updated to be built-in `string` type.
> refactor: remove ValueType enumeration in Go-SDK

- internal/v2/controller/http/command.go
- openapi/v2/device-sdk.yaml
update query parameter, ds-postevent, to ds-pushevent
v2 API is using the incorrect query parameter `ds-postevent`, should be `ds-pushevent`
SDK will accept the correct query parameter `ds-pushevent`
> fix: sync v2 query parameter with ADR

- go.mod
- internal/container/deviceservice.go
- internal/controller/restfuncs_test.go
- internal/controller/restrouter.go
- internal/provision/devices.go
- internal/v2/application/callback.go
- internal/v2/controller/http/callback.go
- openapi/v2/device-sdk.yaml
- pkg/service/manageddevices.go
- pkg/service/managedwatchers.go
- pkg/service/service.go
v2 callback API needs some improvement
fix #745 
fix #762 
- add PUT `/callback/service` for updating device service
- update device/PW callback now is aware of service change: when `ServiceName` changed, we need to either delete or add the device/provisionwatcher instead of just updating it.
> enhance device service v2 callback API

- example/driver/simpledriver.go
- internal/autoevent/executor.go
- internal/v2/application/command.go
- internal/v2/controller/http/command.go
this is a rework of #732 on v2 command API.
SDK ignores the queryParams on PUT request
SDK will parse queryParams in PUT request and add it in `CommandRequest.Attributes`
To verify:
1. add some attributes for DeviceResource, take device-simple for example:
```
name: "Xrotation"
description: "X axis rotation rate"
properties:
valueType: "Int32"
readWrite: "RW"
attributes:
key: "value"
foo: "bar"
```
2. launch device-simple
3. send requests with queryParams, you should be able to see the following logs:
```
$ curl …
```
> process queryParams of url in PUT request

- internal/autoevent/executor.go
- internal/common/utils.go
- internal/transformer/transform.go
- internal/v2/application/command.go
- internal/v2/controller/http/command.go
add a case to create empty event if no readings is generated from
device service driver implementation. Update the return eventDTO type
to pointer accordingly to easily judge if its an empty event and prevent
it from pushing to coredata if it's empty.
> feat: handle no readings generated gracefully

- example/cmd/device-simple/res/Simple-Driver.yaml
- example/cmd/device-simple/res/configuration.toml
- go.mod
- internal/transformer/transformparam.go
- internal/transformer/transformresult.go
- internal/v2/application/command.go
- internal/v2/cache/profiles.go
- internal/v2/cache/profiles_test.go
- openapi/v2/device-sdk.yaml
Close #815 
Upgrade core-contracts lib to apply the v2 device profile changes:
- Upgrade core-contracts lib to use the redesigned device profile
- Update swagger file
> feat: Upgrade core-contracts lib to use redesigned device profile

- pkg/service/manageddevices.go
- pkg/service/managedprofiles.go
- pkg/service/managedwatchers.go
this is needed because profile models are no longer embedded in device models in v2.
Some device service (e.g. device-virtual) used to call `GetDeviceByName().Profiles` to retrieve the device profile, we need the counterpart api to do so.
> feat: add GetProfileByName function API

- go.mod
- internal/common/utils.go
EventClient will set the Content-Type dynamically based on the incoming
event(CBOR for binary and JSON for the other) so that we don't need to
do that in SDK
this is the counterpart of https://github.com/edgexfoundry/go-mod-core-contracts/pull/550
more specific:
https://github.com/edgexfoundry/go-mod-core-contracts/blob/d27e56e5c274da1664efab3f1228ad305b025756/v2/clients/http/utils/common.go#L101-L104
so that we should not hard-code Content-Type in context.
> fix: remove hard-coded Content-Type in SDK

- internal/autoevent/manager.go
- pkg/models/manager.go
- pkg/service/init.go
- pkg/service/main.go
- pkg/service/service.go
There are 2 known issues related to the bootstrap sequence of SDK:
one is #825. Another is when restarting DeviceService, `selfRegister` will update DeviceService in Metadata to reflect the config change, which will eventually callback to device service callback route.
updated sequence:
initRouter
|
initCache
|
ProtocolDriver.Initialize
|
selfRegister -> callback
|
LoadProfiles -> callback
|
LoadDevices -> callback -> ProtocolDriver.AddDevice
> fix: fix bootstrap sequence related bugs

- internal/application/command.go
- internal/autoevent/executor.go
According to v2 api dcoument:
status code 423 is returned, **If the device or service is locked (admin state) or disabled (operating state).**
SDK now only checks the AdminState of Device and DeviceService, the check on OperatingState of Device is missing. 
add the check on OperatingState of Device to meet the spec.
> fix: add device OperatingState check in device command API

- internal/common/utils.go
Content-Type is ignored when pushing event with MessageBus.
add the Content-Type for the MessageEnvelope
> fix: add Content-Type in context for MessageEnvelope

- internal/application/command.go
- internal/cache/profiles.go
- internal/cache/profiles_test.go
- internal/transformer/transform.go
- pkg/service/managedprofiles.go
profile cache design and implementation is not aligned with latest profile model: https://github.com/edgexfoundry/go-mod-core-contracts/pull/540
update profile cache. Also status code 405 can now be correctly returned by device command while trying to read(write) a write-only(read-only) device command.
`DeviceService.ResourceOperation` method has been updated to `DeviceService.DeviceCommand`
> feat: update profile cache to reflect new profile model

- go.mod
- internal/common/consts.go
- pkg/service/main.go
Uses `/1.0/` path set by the SDK
Now uses the `/2.0/` path set by go-mod-bootstrap
BREAKING CHANGE: Consul configuration now under the /2.0/ path
> refactor: Switch to 2.0 Consul path

- internal/transformer/transform.go
- internal/transformer/transform_test.go
- pkg/models/commandvalue.go
- add back the v1 mechanism to generate unique Origin for Event
- use the Origin from ProtocolDriver implementation if it was set for
the Reading, otherwise use the same Origin of the upstream Event
Event origin would be unique under the same device service.
Reading origin could be assigned by ProtocolDriver implementation, otherwise it'll be the same as Event Origin.
> feat: improve Event/Reading Origin logic

- example/cmd/device-simple/res/configuration.toml
- go.mod
- internal/config/types.go
- pkg/service/main.go
- pkg/service/service.go
Currently expecting the Registry/Config Access tokens to be retrieved for files using the file location config settings.
Now uses SecretProvider to retrieve the access tokens.
File location config settings have been removed
BREAKING CHANGE: All App Services running with the secure Edgex Stack now need to have the SecretStore configured, a Vault token created and run with EDGEX_SECURITY_SECRET_STORE=true.
> refactor: Replace file based with use of Secret Provider to get Access Tokens

- internal/application/command.go
v2 device profile defines same resourceOperations for put/set command
the mapping field is default used by get command, so for set command we should do the mapping in reverse order.
> fix: fix set command resourceOperation mapping

- internal/cache/profiles.go
deviceProfileMap was accidentally initialized incorrectly, which will are refer to the same object.
> fix: fix deviceProfileMap refer to the same object

- example/cmd/device-simple/Attribution.txt
- go.mod
- internal/provision/devices.go
use pelletier/go-toml to be consistent across EdgexFoundry go project, also BurntSushi/toml is unmaintained.
> refactor: Replace use of BurntSushi/toml with pelletier/go-toml

- example/cmd/device-simple/res/configuration.toml
- internal/config/types.go
- internal/controller/http/command.go
- internal/controller/http/correlation/handler.go
- internal/controller/http/correlation/middleware.go
- internal/controller/http/restrouter.go
- internal/controller/http/restrouter_test.go
- refactor MiddlewareFunc to correctly pass LoggingClient into it.
- add RequestLimitMiddleware
request size of put command is capped at `Service.MaxRequestSize` defined in configuration.toml file
if exceed, http status 413 will be returned
> feat: add request size middleware for devicecommand

- internal/application/command.go
- internal/cache/provisionwatcher.go
- internal/clients/init.go
- internal/transformer/transform.go
- internal/transformer/transformresult.go
- pkg/models/commandvalue.go
- pkg/service/managedautoevents.go
- pkg/service/manageddevices.go
- pkg/service/managedprofiles.go
- pkg/service/managedwatchers.go
- pkg/service/service.go
`errors.Edgex` implements `error` interface, however normal error threw by standard library doesn't implement `errors.Edgex` 
A common scenario a device service developer might do:
```Go
val, err := customGetValueFunction()
cv, err := sdkModel.NewCommandValue(dr, valueType, val)
```
these code will throw a confusing `Type does not implement 'errors.Edgex...`
use `errors.Edgex`in `internal` package for better logging/debugging; use normal error type in `pkg` package for better device service development experience.
> refactor: return errors.Edgex in internal package, error in pkg package

- Jenkinsfile
Even though the docker image is not pushed, this PR removes `docker-` prefix from docker image name for consistency with other projects.
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
New image name
> ci: update docker image name

- internal/application/command_test.go
- internal/transformer/transform.go
- pkg/models/commandvalue.go
add Tags field in CommandValue struct to allow driver implementor
add custom information if required.
developer can add custom information in `CommandValue`, for example:
```Go
cv, _ := dsModels.NewCommandValue(deviceResourceName, v2.ValueTypeInt32, readingValue)
cv.Tags["foo"] = "bar"
```
> feat: add Event tagging capability

- Makefile
- example/cmd/device-simple/res/configuration.toml
- go.mod
**Dependent on edgexfoundry/go-mod-core-contracts#613**
**Dependent on https://github.com/edgexfoundry/go-mod-bootstrap/pull/216**
Service key constants have the edgex- prefix
Service key constants no longer have the edgex- prefix
Hyphen in Overrides are converted to underscore
BREAKING CHANGE: Service key names used in configuration have changed.
> refactor: Update for new service key names and overrides for hyphen to underscore

- example/cmd/device-simple/res/configuration.toml
- go.mod
- internal/autoevent/manager.go
- internal/clients/init.go
- internal/clients/init_test.go
- internal/common/utils.go
- internal/config/config.go
- internal/config/types.go
- internal/messaging/messaging.go
- internal/messaging/messaging_test.go
- pkg/service/async.go
- pkg/service/init.go
- pkg/service/service.go
SDK uses own version of ServiceInfo with extra settings
SDK now uses common version of ServiceInfo 
Extra settings moved to top level; config settings
Code refactored to adjust to chnages.
BREAKING CHANGE: Device Service configuration items have changed
> refactor: Use common ServiceInfo struct and adjust code/configuration

- example/cmd/device-simple/res/configuration.toml
- internal/autoevent/manager.go
- internal/common/utils.go
- internal/config/config.go
- internal/config/types.go
- internal/messaging/messaging.go
- internal/messaging/messaging_test.go
- pkg/service/async.go
- pkg/service/init.go
- pkg/service/service.go
Recent refactoring moved a few DS specific settings out of Service section (now common struct) to top level settings. Decision in DS WG 5/24/21 is to move these under the `[Device]` section.
Top level individual setting now moved under `[Device]` section
> refactor: Move top level individual config settings under Device section

- internal/application/callback.go
1. if profile not exist, after adding profile to cache map, update profile again
2. if update profile failed, return nil
1. if profile not exist, after adding profile to cache map, dont need to update profile again
2. if update profile failed, return err just like add profile failed
> fix: modify function updateAssociatedProfile return errors

- example/cmd/device-simple/res/configuration.toml
- go.mod
Latest config on SecretStore section with removal of retry-related items and secret path update
Closes: #948
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
With retry items and secret path full
No more retry properties or items from SecreStore config section and update the secret path to be service specific
- [x ] Yes
**Note: all the toml files with these retry item or properties need to be updated: `AdditionalRetryAttempts`, `RetryWaitPeriod`
and the Path property changed to just contain the service specific item as the prefix …
> refactor: Update go-mod-bootstrap version to use latsest config

- example/cmd/device-simple/res/configuration.toml
- internal/config/types.go
Signed-off-by: Iain Anderson <iain@iotechsys.com>
Configuration struct and the example configuration file contain entries for obsolete options InitCmd / InitCmdArgs / RemoveCmd / RemoveCmdArgs
Redundant code and configuration removed
> refactor: remove unimplemented InitCmd/RemoveCmd configuration (#956)

- example/cmd/device-simple/res/configuration.toml
PublishTopicPrefix value is 'edgex/events/' which doesn't allow Core Data to uniquely subscribe just to Device Service Events
PublishTopicPrefix value is 'edgex/events/device' which is unique to Device Services
> refactor: Change PublishTopicPrefix value to be 'edgex/events/device'

- pkg/service/manageddevices.go
- pkg/service/managedwatchers.go
- pkg/service/service.go
Close #987
Assign the id to nil in UpdateDTO before sending out the request to prevent json decode error.
> fix: Fix device service update failed when startup

- CHANGELOG.md
Remove dev churn and add dependency references in CHANGELOG.
> docs: Remove dev churn from CHANGELOG

- openapi/v2/device-sdk.yaml
Update the following example errors in the API YAML file.
1. Add apiVersion field to request body.
2. Replace `frequency` with `interval` for autoEvent fields.
3. Update adminState and OperationgState examples.
Fix #1015.
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
> docs: add apiVersion to request body example

- example/cmd/device-simple/res/profiles/Simple-Driver.yaml
- example/driver/simpledriver.go
- internal/application/command.go
- pkg/models/commandvalue.go
- pkg/models/commandvalue_test.go
Closes #1052
1. Run the simple device 
2. Execute a Set command
3. Execute a Get command to check the value that should be changed.
> fix: Add missing StringArray value type for commandValue

- internal/autoevent/executor.go
fixes #1057
1. Run non secure EdgeX docker stack (stop Device Virtual container)
2. Enable **TRACE** logging for app-rules-engine via Consul
3. Clone branch for this PR
4. Clone Device Virtual
5. Update Device Virtual go.mod to use this branch
6. Build and run Device Virtual with **TRACE** level logging (may have to run second time if profiles not already in Core Metadata)
7. Verify Device Virtual logs has similar to the following: 
```
level=TRACE …
```
> fix: Add setting correlation id when Events created via AutoEvents

- internal/application/callback.go
- internal/controller/http/callback.go
- internal/provision/profiles.go
- pkg/service/manageddevices.go
- pkg/service/managedwatchers.go
Update ProfileCache when adding or updating the Provision Watcher to stay consistent with core metadata
Closes #1053
1. Run core services
2. Run the device-rfid-llrp-go based on the branch https://github.com/marcpfuller/device-rfid-llrp-go
3. check whether the provision watcher is added
> fix: Update ProfileCache when adding or updating the Provision Watcher

- .golangci.yml
- Makefile
- example/driver/simpledriver.go
- internal/autodiscovery/autodiscovery.go
- internal/autodiscovery/discovery.go
- internal/autoevent/executor_test.go
- internal/clients/init.go
- internal/common/utils.go
- internal/controller/http/common_test.go
- internal/controller/http/correlation/middleware.go
- internal/messaging/messaging.go
- internal/provision/devices.go
- internal/provision/profiles.go
- internal/telemetry/telemetry.go
- internal/transformer/transform_test.go
- internal/transformer/transformparam.go
- internal/transformer/transformresult.go
- pkg/models/commandvalue.go
- pkg/models/commandvalue_test.go
- pkg/service/manageddevices.go
- pkg/service/managedprofiles.go
- pkg/service/managedwatchers.go
- pkg/service/service.go
Fixes #1029
Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>
N/A
```make test```
NOTE: There are two remaining issues that need advising.
> feat(security): Enable gosec and default linter set

- README.md
Replace the references of master with jakarta branch
Upgrade the document links from v1.2 to v2.1
Fix the broken link refer to LTS Policy
> docs: Correct document links in README (jakarta branch)

- Makefile
The `-race` flag on unit tests is causing failure in metrics tests which is unrelated to race condition.
Removing for now so CI pipeline builds and address this later.
** N/A **
** N/A **
> ci: Remove -race for unit tests for now to resolve failures in pipeline

- Makefile
- internal/controller/http/common_test.go
> fix: update TestMetricsRequest to not fail when using -race

- example/cmd/device-simple/res/configuration.toml
- example/cmd/device-simple/res/profiles/Simple-Driver.json.example
- example/cmd/device-simple/res/profiles/Simple-Driver.yaml
- go.mod
- go.sum
- internal/config/types.go
- internal/transformer/transform.go
- internal/transformer/transform_test.go
https://github.com/edgexfoundry/edgex-docs/pull/727
1. build the example device-simple from this branch and run with core services
2. `curl -ki http://localhost:59999/api/v2/device/name/Simple-Device01/Rotation` and verify the `units` in the readings
3. set `ReadingUnits` to `false` in the configuration.toml, and send `curl -ki http://localhost:59999/api/v2/device/name/Simple-Device01/Rotation` to verify the `units` is not in the readings
N/A
Close #1120
> feat: Implement ReadingUnits configuration for device profile changes

- internal/controller/http/common.go
- internal/controller/http/common_test.go
- internal/controller/http/restrouter.go
- pkg/service/service.go
Fixes #1136
Signed-off-by: Jennifer Williams <jennifer.m.williams@intel.com>
Build example device service.
Run the example device service.
Send a request to the /config endpoint (Port: 59999).
Verify json response contains the following:
```
"CustomConfiguration": {
"SimpleCustom": {
"OffImageLocation": "./res/off.jpg",
"OnImageLocation": "./res/on.png",
"Writable": {
"DiscoverSleepDurationSecs": 10
}
}
}
```
> fix(configuration): add handling for custom config on /config endpoint

- internal/messaging/messaging.go
> fix: Remove MessageBus Options data from configuration after client created

- internal/messaging/messaging.go
- internal/messaging/messaging_test.go
fix #1162
1. Build device-virtual docker image from this branch and run the security-enabled docker compose
2. GET `/api/v2/config` and verify the response
> refactor: Update to use deepCopy of messageBusInfo to avoid external adds

- example/cmd/device-simple/Attribution.txt
- go.mod
- go.sum
- Upgrade go-mod-messaging to v2.2.1-dev.4
- Upgrade paho.mqtt lib
- Ad golang.org/x/sync into attribution.txt
- Update the paho license to Eclipse Public License 2.0
Close #1176
Run make test
> build: Upgrade go-mod-messaging and paho.mqtt lib

- openapi/v2/device-sdk.yaml
Signed-off-by: Corey Mutter <CoreyMutter@eaton.com>
Noticed this working on issues 419 and 420 in C SDK. Assuming the Go SDK code is the correct behavior (core-metadata thinks so), updating this doc to match.
This IS that docs PR, companion to device-sdk-c PR 421.
VS Code's OpenAPI extensions and viewer didn't flag any problems.
> fix: ProvisionWatcher callbacks return BaseResponse, not 204 No Content.

- internal/application/command.go
- internal/application/command_test.go
Add checking if the value is an empty string and the valueType is not String, the proper error should be returned
Close #1179
1. Deploy device-virtual
2. Inspect the result should look like below:
```
curl curl --location --request PUT 'http://localhost:59882/api/v2/device/name/Random-Float-Device/WriteFloat64Value' \
> --header 'Content-Type: application/json' \
> --data-raw '{"Float64":""}' | json_pp
...
{
"apiVersion" : "v2",
"message" : "request failed, status code: 400, err: …
```
> fix: Put cmd return 400 when updating empty string to NonString type

- internal/application/callback.go
1. run two device services from this branch with `WRITABLE_LOGLEVEL: DEBUG`
2. migrate a device from one to another by updating device's serviceName
3. Verified the device name is correctly received by device-service :
```
level=DEBUG ts=2022-07-28T07:27:46.780732Z app=device-virtual source=callback.go:56 msg="device sample-numeric added"
level=DEBUG ts=2022-07-28T07:27:46.780758Z app=device-virtual source=virtualdriver.go:127 msg="a new Device is added: sample-numeric" …
```
> fix: fix empty device name when updating device's serviceName

- example/cmd/device-simple/res/configuration.toml
- internal/controller/messaging/command.go
- pkg/service/init.go
fix #1189 
1. Run core services from edgex-compose with external MQTT broker and `MESSAGEQUEUE_REQUIRED=true` environment variable
2. Run device-simple from this branch
3. Run `PSUBSCRIBE edgex.command.response.*` in redis container to subscribe to the device command response
4. Send command request to` edgex/command/request/<device>/<command>/<method>` topic. For example send following message to `edgex/command/request/Simple-Device-1/Xrotation/get`:
```json
{ …
```
> feat: subscribe command request via internal messaging

- internal/controller/messaging/command.go
Log informational message and return nil error if empty topic found in MessageQueue topics.  Fixes #1215
Signed-off-by: Alex Ullrich <alex.ullrich@gmail.com>
Start a device service with no CommandRequestTopic configured.
> fix: Skip Subscription to Empty Command Request Topic

- pkg/service/init.go
- pkg/service/main.go
1. Run `device-simple` from this branch with `DEVICE_USEMESSAGEBUS=false` environment variable
2. verify device-simple is running correctly, instead of getting error described in https://github.com/edgexfoundry/device-virtual-go/issues/307#issuecomment-1259120080
> fix: subscribe to internal message bus if UseMessageBus = true

- pkg/service/manageddevices.go
- pkg/service/managedwatchers.go
Remove the duplicated logic of caching profile in the managed device and
provision watcher API, because this is handled by the callback
Fix https://github.com/edgexfoundry/device-sdk-go/issues/1195
1. Write a new Device Service and invoke the AddProvisionWatcher and AddDevice API from the Device Service SDK
2. Invoke PorfileForName API to make sure the profile is in the cache
> fix: Remove redundant logic of chaching profile

- internal/controller/messaging/command.go
fix #1221 
1. Run device-simple from this branch with `WRITABLE_LOGLEVEL=DEBUG` environment variable
2. Send command request to command service via external MQTT
3. Verify the X-Correlation-ID is retrieved correctly:
```
level=DEBUG ts=2022-09-30T02:27:21.546901Z app=device-simple source=command.go:67 msg="Command request received on message queue. Topic: edgex/command/request/device-simple/#, Correlation-id: 14a42ea6-c394-41c3-8bcd-a29b9f5e6835 "
level=DEBUG …
```
> fix: revert using custom-typed key for Context value

- example/cmd/device-simple/res/configuration.toml
- internal/common/utils.go
- internal/common/utils_test.go
- pkg/service/init.go
closes #1238
https://github.com/edgexfoundry/edgex-docs/pull/881
Run non-secure EdgeX Stack
Build Device Simple from this branch
Run Device Simple from command-line with logging set to DEBUG
Verify the following are in the log file once first autoevent fires
```
"EventsSent metric has been registered and will be reported (if enabled)"
"ReadingsSent metric has been registered and will be reported (if enabled)"
```
After 30secs or so verify the following in the log file
``` …
```
> feat: Add metrics for count of Events and Readings sent

- Makefile
- example/cmd/device-simple/Attribution.txt
- example/cmd/device-simple/Dockerfile
BREAKING CHANGE: ZeroMQ MessageBus capability no longer available
Build branch locally without gcc and zmq libs available.
Verify sample builds and run as expected.
> feat!: Remove ZeroMQ MessageBus capability

- internal/application/command.go
Signed-off-by: Felix Ting <felix@iotechsys.com>
> fix: typo "DeviceResourece" -> "DeviceResource" in error message

- internal/controller/http/command_test.go
- openapi/v2/device-sdk.yaml
BREAKING CHANGE: ds-pushevent and ds-returnevent to use bool true/false instead of yes/no
related: https://github.com/edgexfoundry/go-mod-core-contracts/pull/782
https://github.com/edgexfoundry/edgex-docs/pull/917 and the Swagger file in this repo
build core-command and device-virtual docker images based on the changes and run docker-compose.yml
The following commands work as expected:
```
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=true
curl …
```
> refactor!: Use bool types for command parameters to be more consistent

- example/cmd/device-simple/res/configuration.toml
- internal/common/utils.go
- internal/common/utils_test.go
- internal/config/types.go
- pkg/service/main.go
BREAKING CHANGE: Removed the 'Device.UseMessageBus' config, the code for sending event via core-data REST client and the 'Clients.core-data' dependency
MessageBus is always enabled in 3.0 for sending events and receiving system events for callbacks.
closes #1296
1. Run device-simple from this branch
2. Run `PSUBSCRIBE edgex.events.device.*` in redis container to subscribe to the auto event messages
3. Check the autoevent messages are received by `redis` container: …
> feat!: remove UseMessageBus config in 3.0

- example/cmd/device-simple/res/configuration.toml
BREAKING CHANGE: use MQTT wild cards + for single level and # for multiple levels
https://github.com/edgexfoundry/edgex-docs/pull/953
1. Build and run device-simple
2. create a device and receive the system event correctly
```
level=DEBUG ts=2023-02-06T03:54:48.837716Z app=device-simple source=callback.go:55 msg="System event received on message queue. Topic: edgex/system-events/core-metadata/device/+/device-simple/#, Correlation-id: aff63bcd-93b2-43ce-afb6-b7d38535ce13 "
```
> refactor!: Update config for message bus topic wild cards

- internal/common/utils.go
- internal/common/utils_test.go
- internal/transformer/transform.go
fix #1294 
1. Add device resource tags to reading
2. Add device command tags to event
3. Add device tags to event
Note: Device tags take precedence over Device Command tags.
Signed-off-by: Felix Ting <felix@iotechsys.com>
1. Run non-secure EdgeX Stack
2. Based on this branch, modify the device configuration of Device Simple to add device tags
simple-device.toml
```
[[DeviceList]]
Name = "Simple-Device01"
ProfileName = "Simple-Device"
Description = "Example of Simple Device"
Labels = [ "industrial" ]
[DeviceList.Tags] …
```
> feat: Add resource, command, and device tags to reading/event

- internal/application/callback.go
- internal/controller/http/callback.go
- internal/controller/http/restrouter.go
- internal/controller/messaging/callback.go
- openapi/v3/changes.txt
- openapi/v3/device-sdk.yaml
BREAKING CHANGE: remove /callback/watcher and /callback/watcher/name/{name} REST endpoints
1. build and run device-simple from this branch and core-metadata from https://github.com/edgexfoundry/edgex-go/pull/4346
2. add/update/delete a provision watcher
3. verified the callbacks are successfully triggered by system event:
- add a provision watcher
```
level=DEBUG ts=2023-02-13T09:48:21.488495286Z app=device-simple source=callback.go:56 msg="System event received on …
```
> feat!: replace REST provision watcher callbacks with System Events

- internal/common/utils.go
Previous refactoring missed adding 'device' to event publish topic
> fix: Add missing 'device' to event publish topic

- openapi/v3/changes.txt
- openapi/v3/device-sdk.yaml
Per https://github.com/edgexfoundry/go-mod-core-contracts/pull/800, the Device DTO is added with a new field `properties`, so the swagger file needs to be updated correspondingly.
Moreover, this commit also updates the swagger file to remove those fields that had been taken out of Device DTO before:
- created
- modified
- serviceId
- profileId
This commit also adds back a newly created field `tags` into the Device DTO.
> fix: Update swagger to match latest changes in go-mod-core-contracts Device DTO

- internal/common/utils.go
- internal/controller/http/correlation/middleware.go
- internal/controller/http/restrouter.go
- internal/controller/messaging/command.go
- Use escaped resource name for message bus topic
- Unescape the URL path
Close #1334
> feat: Accept URL escape for device command name and resource name

- pkg/service/init.go
- pkg/service/service.go
This will prevent errors from occurring when driver.Initialize causes UpdateDevice to be triggered/called.
- [N/A] I have added unit tests for the new feature or bug fix (if not, why?) - No existing unit tests to update
- [N/A] I have opened a PR for the related docs change (if not, why?)
Call UpdateDevice within driver.Initialize and ensure the device is not removed from cache.
fixes #1358
> fix: assign device service in dic before driver.Initialize

- example/cmd/device-simple/res/devices/simple-device.json.example
- example/cmd/device-simple/res/devices/simple-device.toml
- example/driver/simpledriver.go
- go.mod
- go.sum
- pkg/service/async.go
related to edgexfoundry/go-mod-core-contracts#592
consume ProtocolProperties type changes in go-mod-core-contracts. AutoDiscovery handler will still parse property as string type and compare with ProvisionWatcher regex identifier.
1. Run `device-simple` from this branch with `DEVICE_DISCOVERY_ENABLED: true` 
2. Verify autodiscovery is working correctly by seeing logs like:
```shell
level=INFO ts=2023-03-08T03:37:44.264246Z app=device-simple source=async.go:105 msg="Adding discovered device Simple-Device02 to Metadata" …
```
> feat: Device ProtocolProperties have typed values

- go.mod
- go.sum
- internal/config/config.go
Run non-secure EdgeX Stack
Build and run device simple from this branch
Verify logs contain:
```
"listening for private config changes"
"listening for all services common config changes"
"listening for device service common config changes"
```
In Consul add `Writable/Telemetry/Interval` to `edgex/v3/core-common-config-bootstrapper/device-services` with value of 20s
Verify the log contains:
```
"Writeable configuration has been updated from the Configuration Provider"
"Telemetry interval has been updated. Processing new …
```
> feat: Consume watch for common Writable config changes

- internal/application/command.go
- internal/common/utils.go
- internal/controller/http/command.go
- internal/controller/http/command_test.go
- internal/controller/messaging/command.go
- internal/transformer/transform.go
- internal/transformer/transform_test.go
- pkg/service/async.go
Similiar to GET command with 'ds-pushevent=true', publish an event with updated resource(s) value to messageBus as long as the resource/command is not write-only.
closes #1271
https://github.com/edgexfoundry/edgex-docs/pull/983
1. Run `device-simple` from this branch
2. Subscribe to edgex internal event topics in `redis` container:
```shell
$ docker exec -it edgex-redis /bin/sh
/data # redis-cli
127.0.0.1:6379> PSUBSCRIBE edgex.events.device.*
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) "edgex.events.device.*"
3) …
```
> feat: publish event with updated value for PUT command

- go.mod
- go.sum
- internal/transformer/transformparam.go
- internal/transformer/transformresult.go
- internal/transformer/transformresult_test.go
BREAKING CHANGE: support mask,shift,base,scale,offset in numeric data type
related to edgexfoundry/go-mod-core-contracts#770
https://github.com/edgexfoundry/edgex-docs/pull/982
> refactor!: update data types in ResourceProperties

- internal/transformer/transform.go
Retrieve the event tags before mapping cmd value to prevent tags lost.
Close #1397
Run unit test and test the command API.
> fix: Retrieve the event tags before mapping cmd value

- example/driver/simpledriver.go
- internal/application/command.go
- internal/autoevent/executor.go
- internal/cache/profiles.go
- internal/cache/profiles_test.go
- internal/common/utils.go
- internal/controller/http/command.go
- internal/controller/http/command_test.go
- internal/controller/messaging/command.go
- openapi/v3/device-sdk.yaml
SDK now default treat resource name as regex pattern and will return
readings whose resource name matches against the regex pattern.
For protocol whose resource name contains special character, specify
'ds-regexcmd=false' in query parameter to make it as normal resource name.
closes edgexfoundry/edgex-go#4279
https://github.com/edgexfoundry/edgex-docs/pull/991
1. Run `device-simple` from this branch
2. Run core-command with URL-escaped regex command name: `.rotation` or `[A-Z]+rotation` and query parameter `ds-regexcmd=true`
```shell
$ …
```
> feat: enable regex for executing GET command

- internal/application/command.go
- internal/cache/profiles.go
- internal/cache/profiles_test.go
Use `CompilePOSIX` and `FindString` and check that the string found is the entire resource name
closes #1418
1. Build and Run `device-virtual` from this branch
2. Verify autoevent `Uint16` returns only 1 reading `Uint16`
> fix: update regex resourceName match logic

- internal/controller/http/correlation/middleware.go
- internal/controller/messaging/command.go
BREAKING CHANGE: Use PathUnescape for decoding API path to consist with the change from MQTT topic, the MQTT topic path will encode with url.PathEscape.
Close #1443
Run core services and device service to check whether the event can publish to the message bus.
> feat!: Using url.PathUnescape for decoding API path

- example/cmd/device-simple/res/configuration.yaml
- go.mod
- go.sum
- internal/config/config.go
- pkg/service/service.go
Dev Mode is used when running service locally with the other services running in Docker (aka hybrid mode). This causes all the Host settings pulled from common configuration to be overridden with the value localhost.
https://github.com/edgexfoundry/edgex-docs/pull/1040
build device-simple with this branch
run `device-simple -cp`
Verify it hangs do to Subscribe error issue
run `device-simple -cp -d`
Verify service successfully bootstraps
Enable DEBUG logging from Consul
Verify service is publishing events
> feat: Consume new -d/--dev Dev Mode command-line flag

- pkg/service/manageddevices.go
- [N/A] I have opened a PR for the related docs change (if not, why?)
- Build device-onvif-camera using the lastet sdk
- Run the service and see that cameras are added to the system
- Observe that there are errors updating the device during the checkstatus calls:
```
failed to find Device device-onvif-camera in cache
```
- Clone this branch to the same top-level directory as device-onvif-camera
- Build device-onvif-camera using this code (use replace in go.mod file)
```
replace ( …
```
> fix: typo in calls to GetDeviceByName

- example/cmd/device-simple/res/configuration.yaml
- internal/provision/common.go
- internal/provision/common_test.go
- internal/provision/devices.go
- internal/provision/devices_test.go
- internal/provision/mockdic_test.go
- internal/provision/profiles.go
- internal/provision/profiles_test.go
- internal/provision/provisionwatchers.go
- internal/provision/provisionwatchers_test.go
**Non-Secure testing**
1. pull the latest code and build device simple
2. run the non-secure edgex stack
3. run device-simple with its standard configuration
4. stop device-simple 
5. modify the configuration to point to a custom index.json file (created in internal/uri-test-files/*/index.json)
6. run device-simple and ensure that the index.json works without errors
** Secure testing**
1. create a private repo
2. run the secure edgex stack
3. use both configuration options - file and URI
4. run and ensure device-simple …
> feat: Implement URI for Profile, Device, & Provision Watcher

- go.mod
- go.sum
- pkg/service/init.go
- pkg/service/service.go
with better error message handling from the go-mod-bootstrap PR, there is some logic needs to be fixed to avoid the app being crashed.
Closes: #1479
- git clone this PR
- run `make` to compile device sdk in the project base directory
- change the directory to device simple under ./example/cmd/device-simple
- run `./device-simple` without -cc flag to see the results of better error handling messages.
- repeat as needed.
-
> feat: better error handling when running in hybrid mode but common config is missing

- internal/common/utils.go
- internal/controller/messaging/callback.go
- internal/controller/messaging/command.go
- internal/controller/messaging/validation.go
Use escaped for message bus topic
- service name
- profile name
- device name
Close #1495
Run core service and device service to test the API.
> feat: Accept Url escape in API path

- internal/provision/common.go
- internal/provision/common_test.go
- internal/provision/profiles.go
Closes #1504
1. Download compose file from edgex-compose
2. Modify the go.mod for device-virtual to add this replace `replace github.com/edgexfoundry/device-sdk-go/v3 => github.com/ejlee3/device-sdk-go/v3 v3.0.0-20230907221428-f6709ffcbf22` to use the new device-sdk.
3. Build the docker image for device-virtual.
3. Change the image name for device virtual to `docker.io/edgexfoundry/device-virtual:0.0.0-dev` and add the following variables to the edgex-compose/docker-compose.yml under device-virtual > environment to …
> fix: Adjust GetFileType() function for new secret URI format

- go.mod
- go.sum
- internal/common/utils.go
- internal/controller/messaging/callback.go
- internal/controller/messaging/command.go
- internal/controller/messaging/validation.go
BREAKING CHANGE: Allow NameFieldPath configurable by checking whether the NameFieldPathEscape enable.
Related PRs are opened, you can refer to https://github.com/edgexfoundry/edgex-go/issues/4673#issuecomment-1709699336 and run services to verify the API.
> feat: Allow NameFieldPath configurable

- internal/application/command.go
- internal/cache/devices.go
- internal/cache/devices_test.go
- internal/cache/init.go
- internal/common/utils_test.go
- internal/controller/http/command_test.go
- internal/provision/mockdic_test.go
- internal/transformer/transform_test.go
- pkg/service/async.go
fixes #1470. Add device last connected metrics to Get/Set command.
> feat: Add device last connected metrics

- internal/application/command.go
close https://github.com/edgexfoundry/device-sdk-go/issues/1553
> fix: Set proper transform flag for Set command

- internal/cache/profiles.go
- internal/provision/profiles.go
Fix https://github.com/edgexfoundry/device-sdk-go/issues/1586
> fix: Use atomic operation to provision profile

- internal/application/profilescan.go
- internal/controller/http/discovery.go
Close https://github.com/edgexfoundry/device-sdk-go/issues/1608
> refactor: Refine the discovery and scan logs

- internal/autoevent/manager.go
Auto Events should not be triggered if the Device Profile is empty or the Device is locked
Close https://github.com/edgexfoundry/device-sdk-go/issues/1613
> fix: Don't run auto events for empty profile

- internal/transformer/transform.go
- internal/transformer/transformresult.go
- pkg/models/commandvalue.go
Allow reading value to be null
Test with device simple.
> feat: Allow reading value to be null

- go.mod
- go.sum
- internal/application/command.go
- internal/autoevent/executor_test.go
- internal/transformer/transform.go
- internal/transformer/transform_test.go
- internal/transformer/transformparam.go
Using isNull instead of nil reading value
- run make test
- test with simple DS
This PR is based on the core-contracts https://github.com/edgexfoundry/go-mod-core-contracts/pull/935
> feat: Using isNull field instead of nil reading value

- go.mod
- go.sum
- internal/autoevent/executor.go
- internal/autoevent/executor_test.go
The onChange flag in Device AutoEvent can prevent any non changed values sent out. The onChangeThreshold could provide the advanced feature, and the default value is 0, any changed value that exceeds (>) bounds shall be published. For example, Current_value - Current_prev > 0.01 shall be published where "Current_value" is the new value and "Current_prev" is the previously published value.
Run make test, test with core services and device-simple.
> feat: Implement AutoEvent onChangeThreshold

- internal/application/callback.go
- internal/application/command.go
- internal/application/devicereturn.go
- internal/autoevent/executor.go
- internal/cache/devices.go
- internal/config/types.go
- internal/container/allowedfailstracker.go
- internal/container/atomicint.go
- internal/container/deviceservice.go
- internal/controller/http/command_test.go
- pkg/service/init.go
fix: #1665 
https://github.com/edgexfoundry/edgex-docs/pull/1407
Run Edgex stack using Edgex compose-builder
```
make run no-secty modbus-sim
```
Run device-modbus with this version of the device sdk and the following configuration
```
Writable:
LogLevel: INFO
Service:
Host: localhost
Port: 59901
StartupMsg: device modbus started
MessageBus:
Optional:
ClientId: device-modbus
Device:
ProfilesDir: ""
DevicesDir: ""
AllowedFails: 1
DeviceDownTimeout: 10
```
Upload device profile and onboard a device
```
curl http://localhost:59881/api/v3/deviceprofile/uploadfile -F "file=@modbus.test.device.profile.yml"
```
```
curl http://localhost:59881/api/v3/device -H "Content-Type:application/json" -X POST \
-d '[
{
"apiVersion" : "v3", …
```
> feat: Add device up/down detection

- internal/autoevent/executor.go
This change ensures AutoEvent execution happens at the given interval. If `readResource` takes longer than the AutoEvent interval, events will come at the speed of the read function.
fix: #1627 
1. Use [device-simple](https://github.com/edgexfoundry/device-sdk-go/tree/main/example). Modify the [HandleReadCommands](https://github.com/edgexfoundry/device-sdk-go/blob/ef783aee92ebef88ebd5d55046da9029b3983fb4/example/driver/simpledriver.go#L180-L182) method in simpledriver.go to include a time.Sleep call to simulate a delay …
> feat: Ensure AutoEvent execution happens at the configured interval

- go.mod
- go.sum
- internal/cache/devices.go
- internal/cache/profiles.go
- internal/cache/provisionwatcher.go
Since the cache share data, the map and slice should be cloned to prevent concurrent read write error.
Closes #1710
> fix: Fix cache concurrent read write error

- example/cmd/device-simple/res/configuration.yaml
- internal/autoevent/executor.go
- internal/autoevent/executor_test.go
- internal/config/types.go
Resolves #1705. Add SendChangedReadingsOnly config to only send updated auto event readings if the value is true.
> feat: Add SendChangedReadingsOnly config to only send updated values

- README.md
- internal/provision/devices.go
- internal/provision/devices_test.go
- internal/provision/profiles.go
- internal/provision/profiles_test.go
- pkg/service/init.go
- pkg/service/service.go
This change is to partially address the https://github.com/edgexfoundry/device-sdk-go/issues/1745 issue.  This PR will cover the devices and the device profiles being allowed to be overwritten.  If these changes are acceptable, I will go ahead and also make the changes in regard to the provision watchers.  I have not used the provision watchers feature of EdgeX before but will look into it in order to make the required changes for those.
Please let me know where the best place to update the documentation on the new flags added to the device service SDK.
Note that I have a colleague that is currently actively working on this same change for the C Device SDK.
To test, simply start the "device-simple" example, with un-modified profiles and device files.  Then, stop the service, and make a …
> feat: Issue-1745 Add cli flag to overwrite existing device profiles and devices in core-metadata
