devices.go, profiles.go
This should fix the issue commented in #17 and maybe close the issue itself
=> Devices doesn't work properly with two or more devices

command_test.go, config.go, examples/simple/cmd/res/configuration.toml, service.go, utils.go, utils_test.go
Signed-off-by: Andriy Popovych <popovych.andrey@gmail.com>
=> Consul integration

.gitignore, clientinitializer.go, clientinitializer_test.go, config.go, examples/simple/cmd/res/configuration.toml, service.go
https://github.com/edgexfoundry/device-sdk-go/issues/7
Signed-off-by: Bruce <weichou1229@gmail.com>
=> Add service dependency startup logic

clientinitializer.go, config.go, examples/simple/cmd/res/configuration.toml, mock/mock_addressableclient.go, mock/mock_scheduleclient.go, mock/mock_scheduleeventclient.go, profiles.go, schedules.go, schedules_test.go, service.go
https://github.com/edgexfoundry/device-sdk-go/issues/31
=> Create schedule & schedule events on startup

clientinitializer.go, clientinitializer_test.go, config.go, mock/mock_addressableclient.go, mock/mock_scheduleclient.go, mock/mock_scheduleeventclient.go, schedules.go, schedules_test.go, service.go
https://github.com/edgexfoundry/device-sdk-go/issues/53
=> Change copyright headers

devices.go, update.go, update_test.go
=> Implemented callback to handle device adminState

examples/simple/cmd/res/configuration.toml
https://github.com/edgexfoundry/device-sdk-go/issues/57
=> Modify schedule configuration with ISO 8601 expression

devices.go, devices_test.go, mock/mock_addressableclient.go, mock/mock_deviceclient.go, mock/mock_scheduleclient.go, mock/mock_scheduleeventclient.go
https://github.com/edgexfoundry/device-sdk-go/issues/9
=> Add public Service methods to remove or update Devices

async.go, clientinitializer.go, clientinitializer_test.go, cmd/main.go, cmd/res/configuration.toml, command.go, command_test.go, common/config.go, common/consts.go, common/utils.go, common/utils_test.go, config/loader.go, config/loader_test.go, driver/simpledriver.go, profiles.go, protocoldiscovery.go, registry/consul.go, registry/consulendpoint.go, registry/registry.go, schedules.go, schedules_test.go, service.go, update_test.go
restructured the main component according to the document:
https://docs.google.com/document/d/1nXIYFGoxepd7ctkwEmZMzxxdDkymNe5QZjf5YDT7h4Q/edit?usp=sharing
passed all existing unit test and basic manually tests
moved configuration loading logic to config package
moved configuration loading behavior to main package
moved common models and utils to common package
=> restructure the main and related packages

devices.go
removed the code to disable Device OperatingState when creating Device Cache
=> removed the code to disable Device OperatingState when creating Device Cache

clientinitializer.go, clientinitializer_test.go, command_test.go, devices_test.go, schedules.go, schedules_test.go, utils.go, watchers.go
This PR cleans up import statement style and also fixes a mis-formatted copyright header.
=> Cleanup style

devices.go, service.go
=> Fixed invalid time format in origin fields

command.go
Fixed #72. Also added event origin time
=> Now events are sent in another goroutine.

async.go
Fix #94
To put transform error message into the reading value
=> Correct the transform failed handling in async.go

service.go
=> Moved service name assignment prior to load config

internal/handler/command.go
=> Correct the Value Descriptor query for PUT command

internal/cache/devices.go, internal/handler/callback.go
=> Added device, device profile and addressable callbacks

internal/controller/restrouter.go, internal/handler/command.go, internal/scheduler/executor.go
=> Added /device/name/{name}/{command} API

internal/provision/profiles.go, pkg/startup/bootstrap.go, service.go
Related with PR #111 
Also fixed some log messages.
=> Fixed startService() initialization behavior

README, README.md
=> Rename and update README

internal/cache/valuedescriptors.go, internal/clients/init_test.go, internal/controller/restfuncs_test.go, internal/provision/profiles.go
=> Modify ValueDescriptor Id as a string

internal/common/utils.go, internal/mock/mock_addressableclient.go, service.go
=> Replace Replace ErrNotFound to NewErrServiceClient

internal/handler/command.go
=> Make Put cmd accept both simple JSON and array for Delhi

internal/transformer/transformparam.go, internal/transformer/transformresult.go, internal/transformer/transformresult_test.go
The Scale will be parsed to float first for transformation
fix #151
=> Make Scale can be float data type

internal/cache/devices.go, internal/cache/profiles.go, internal/common/utils.go, internal/controller/restfuncs_test.go, internal/handler/callback.go, internal/mock/mock_deviceclient.go, internal/provision/devices.go, internal/provision/profiles.go, manageddevices.go, managedprofiles.go
The bson id data type of device and profile is replaced with string
fix #156
=> Replace id data type of device and profile

internal/handler/command.go
=> Use DeviceResources instead of ValueDescriptors for consistency

example/cmd/device-simple/res/configuration.toml, example/cmd/device-simple/res/docker/configuration.toml, internal/handler/command.go
fix #141
Also made a minor fix for Attribution.txt
=> Make Put command accept simple JSON map

async.go, example/driver/simpledriver.go, go.mod, internal/cache/init.go, internal/cache/profiles.go, internal/common/utils.go, internal/handler/callback.go, internal/handler/command.go, internal/mock/mock_addressableclient.go, internal/mock/mock_deviceclient.go, internal/mock/mock_scheduleclient.go, internal/mock/mock_scheduleeventclient.go, internal/mock/mock_valuedescriptorclient.go, internal/provision/devices.go, internal/provision/profiles.go, internal/provision/schedules.go, internal/transformer/transformresult.go, manageddevices.go, managedprofiles.go, pkg/models/commandrequest.go, pkg/models/protocoldriver.go, service.go
To meet the edgex-go PR #1029
fix #168
=> Rename DeviceObject to DeviceResource

Attribution.txt, async.go, go.mod, internal/cache/init.go, internal/common/consts.go, internal/common/utils.go, internal/handler/callback.go, internal/provision/devices.go, internal/provision/profiles.go, internal/provision/schedules.go, internal/transformer/transformresult.go, manageddevices.go, managedprofiles.go, service.go
To meet edgexfoundry/edgex-go#1067
Add basic tracing and metrics via a simple correlation ID
fix #169
=> Add context for each client call in edgex

internal/handler/status.go
#179
Signed-off-by: difince <dianaa@vmware.com>
=> /ping endpoint returns the version instead of "pong" msg

internal/common/types.go, internal/config/loader_test.go, internal/config/test/configuration.toml, service.go
Fix #78 
Already reviewed at https://github.com/edgexfoundry/device-sdk-go/pull/203
=> Add protocol driver's customizable configuration

internal/common/consts.go
additional commit to issue #179 
Signed-off-by: difince <dianaa@vmware.com>
=> Remove unused constant StatusResponse "Pong"

service.go
[#167](https://github.com/edgexfoundry/device-sdk-go/issues/167)
Signed-off-by: Alexandre Courouble <acourouble@vmware.com>
=> Add more information to log in start up time

go.mod, internal/controller/restfuncs.go
To resolve [issue #220](https://github.com/edgexfoundry/device-sdk-go/issues/220) and prepare for publish of CBOR readings to Core Data.
=> Use constants from core contracts

example/driver/simpledriver.go, go.mod, internal/clients/init.go, internal/clients/init_test.go, internal/common/globalvars.go, internal/controller/restfuncs_test.go, internal/transformer/transformresult_test.go, pkg/models/protocoldriver.go
=> Change import package name logging to logger

go.mod, internal/config/loader.go, internal/config/loader_test.go, internal/endpoint/endpoint.go
=> Updates for latest go-mod-registry refactoring

go.mod
=> Update to go-mod-registry fix for service crash

example/cmd/device-simple/res/configuration.toml, example/cmd/device-simple/res/docker/configuration.toml, internal/autoevent/executor.go, internal/autoevent/executor_test.go, internal/autoevent/manager.go, internal/common/consts.go, internal/common/types.go, internal/controller/restfuncs.go, internal/handler/callback/callback.go, internal/handler/command.go, internal/provision/devices.go, service.go
Create autoevent package
Trigger AutoEvent when starting up
Restart AutoEvents when the device is updated
Start AutoEvents when new device is created
Stop AutoEvents when the device is deleted or service is stopped
Add AutoEvent sample to device-simple
fix #215
=> Implement AutoEvent mechanism

internal/controller/restfuncs.go
Addresses issue #258  
Signed-off-by: tobiasmo1 <tobias.mosby@intel.com>
=> Push core-data event for JSON/CBOR GET commands

async.go, example/driver/simpledriver.go, go.mod, internal/common/utils.go, internal/handler/command.go, internal/mock/mock_devicevirtualdriver.go, internal/mock/mock_eventclient.go, internal/transformer/transformresult.go, internal/transformer/transformresult_test.go, pkg/models/commandrequest.go, pkg/models/commandvalue.go, pkg/models/commandvalue_test.go
Minimize the structure of CommandValue and CommandRequest
Modify the related code to meet this refactoring
Modify EventClientMock to resolve the compile error
fix #213
=> Refactor CommandValue and CommandRequest

example/cmd/device-simple/res/Simple-Driver.yaml, internal/handler/command.go, internal/handler/command_test.go, internal/provision/profiles.go
Create and Query ValueDescriptor according to DeviceResource name
Modify device-simple profile to meet this change
fix #150
=> Make Reading and ValueDescriptor are based on DeviceResource name

internal/handler/command.go, internal/handler/command_test.go
It can only process Core Command before
fix #218
fix #227
=> Make CommandHandler can process Device Resource

example/driver/simpledriver.go, manageddevices.go, managedprofiles.go, pkg/models/commandrequest.go, pkg/models/commandvalue.go, pkg/models/event.go, pkg/models/protocoldriver.go, pkg/startup/bootstrap.go, service.go
Refine the wording and add the missing part
fix #77
=> Review and refine go doc for public packages

pkg/models/commandvalue_test.go
Resolves issue #284 with examples of MVP binary command value tests.
Confirmed passing and coverage generation with **make test**.
=> Add example NewBinary CommandValue tests

internal/autoevent/executor.go
Use sync.Mutex to lock the map when accessing it
fix #311
=> [Edinburgh] Make the lastReadings map in autoevent thread safe

internal/autoevent/executor.go
Use sync.Mutex to lock the map when accessing it
fix #311
=> Make the lastReadings map in autoevent thread safe

internal/config/environment.go, internal/config/environment_test.go
https://github.com/edgexfoundry/device-sdk-go/issues/332
Signed-off-by: Iain Anderson <iain@iotechsys.com>
=> Support setting registry location with a single environment variable

api/oas3.0/device-sdk.yaml
Fix #352 
Check in the device-sdk API document from https://app.swaggerhub.com/apis-docs/edgex-test/device-sdk/1.1.x-oas3.
=> Add device-sdk API document

internal/provision/profiles.go
The plan it to move whole ValueDescriptor management logic to Core Metadata in Geneva.  For now, there is a config called EnableValueDescriptorManagement in Core Metadata to control whether the management responsibility is under Core Metadata or Device Service SDK.
This commit is adding the logic to retrieve the is config value from
Core Metadata and skip the ValueDescriptor creation if it is true.
Fix https://github.com/edgexfoundry/device-sdk-go/issues/318
=> Move Creation of ValueDescriptors to Metadata

internal/provision/profiles.go
In the provision stage, the new and deprecated fields of ResourceOperation are not handle as expected, because they are loaded from YAML, not JSON. Adding logic to make the following value transition can fix this issue.
ResourceOperation.Object -> ResourceOperation.DeviceResource
ResourceOperation.Resource -> ResourceOperation.DeviceCommand
Fix https://github.com/edgexfoundry/device-sdk-go/issues/376
=> Handle the field name change in RO

service.go
start the web server listening before profile and device provision, and then the metadata callback can be received normally
Fix https://github.com/edgexfoundry/device-sdk-go/issues/380
=> Move web server listening before device provision

service.go
Signed-off-by: Iain Anderson <iain@iotechsys.com>
=> Revert to previous ordering between async channel create and driver init

RELEASE-NOTES.txt, pkg/models/commandvalue.go, pkg/models/commandvalue_test.go
Duplicate of #346 to address #345 for Fuji release.
=> binary NewCommandValue consistency (fuji)

Attribution.txt, go.mod, internal/common/consts.go, internal/config/loader.go, pkg/startup/bootstrap.go
Commit the changes in #396 and #401 on fuji branch
=> Update the --registry command line options

Attribution.txt, go.mod, internal/autoevent/executor.go, internal/autoevent/executor_test.go
Commit changes in #403 onto fuji branch
=> Add Binary Support for OnChange Autoevents 

internal/common/consts.go, internal/common/utils.go, internal/common/utils_test.go, internal/handler/command.go
Commit changes in #398 onto fuji branch
=> [Fuji] Filter out query parameters with prefix "ds-" to ProtocolDriver

Makefile, bin/test-attribution-txt.sh, bin/test-go-mod-tidy.sh, example/cmd/device-simple/Attribution.txt
=> Move Attribution.txt and add test target for out-of-date in Makefile

internal/handler/command.go, internal/handler/command_test.go, internal/mock/consts.go, internal/mock/data/device/New-Device-02.json, internal/mock/mock_deviceclient.go
GET/PUT command should return code 423 when the operatingState of device set to DISABLED
Fix #390
=> GET/PUT cmd should return 423 when the operatingState of device set to DISABLED

internal/common/globalvars.go, internal/config/loader.go, pkg/startup/bootstrap.go, service.go
Cherry-picked commits in #383 to master branch
=> Add option to overwrite registry with local config

internal/handler/command.go, internal/handler/command_test.go, internal/mock/consts.go, internal/mock/data/device/New-Device-02.json, internal/mock/mock_deviceclient.go
GET/PUT command should return code 423 when the operatingState of device set to DISABLED
Signed-off-by: weichou <weichou1229@gmail.com>
(cherry picked from commit 5245bcb1aa583dff863c27fe7fe23e4dad602196)
Fix #390
=> Cmd should return 423 for operatingState DISABLED device

pkg/models/commandvalue.go
fix #433 
Signed-off-by: Felix Ting <felix@iotechsys.com>
=> Update comments on BinValue in commandvalue.go

RELEASE-NOTES.txt
Update RELEASE-NOTE for fuji branch to meet the change in v1.1.2
Fix #443
=> Update RELEASE-NOTE for v1.1.2

internal/config/loader.go
Signed-off-by: Brandon Forster <me@brandonforster.com>
=> Fixed issue where errors were not handled during configuration load.

.github/PULL_REQUEST_TEMPLATE.md
=> Update commit message guideline URL

README.md, pkg/models/commandvalue.go
Fix #460 
Issue Number: #460 
Describe float encoding usage and add the information in Readme to describe the situation of base64 encoding for float type.
=> Update readme and godoc for float encoding usage

pkg/service/manageddevices.go
=> Check device profile from metadata in AddDevice

example/cmd/device-simple/res/Simple-Driver.yaml, internal/common/utils.go, internal/handler/command.go, pkg/models/commandvalue.go, pkg/service/async.go
=> Add new fields on Reading

internal/handler/callback/profile.go
=> call updateDevice after updating device profile

internal/handler/callback/device.go
=> Update porfile in add device callback handler

example/cmd/device-simple/res/configuration.toml, go.mod
=> Allow device service to set empty logfile path

pkg/service/manageddevices.go
=> Add UpdateDeviceOperatingState function

internal/common/utils.go
=> Assign FloatEncoding into Reading

internal/autoevent/manager.go
=> Add check in StopAutoEvents

example/cmd/device-simple/res/Simple-Driver.yaml, example/driver/simpledriver.go, internal/handler/command.go, pkg/models/commandvalue.go, pkg/models/commandvalue_test.go
=> Support array data type in Readings

go.mod
environment overrides can't be uppercase.
Issue Number: #502
Now environment overrides can be uppercase.
=> feat(environment): Allow uppercase environment overrides

internal/autoevent/manager.go, pkg/service/init.go, pkg/service/service.go
=> Refactor BootstrapHandler

internal/clients/init.go
=> Fix fetch configuration 404 error

RELEASE-NOTES.txt
=> Add release note for Geneva

internal/controller/restfuncs_test.go, internal/handler/callback/device.go, internal/handler/callback/provisionwatcher.go
move the update profile logic into a function for better usability and apply it in both add device and update device callback handler.  
Also refactor the device callback handler. 
Fix #513 
=> update profile in update device callback handler

RELEASE-NOTES.txt
=> docs: update release notes

go.mod
Issue Number: #518
Fixes this issue edgexfoundry/go-mod-bootstrap#72
=> fix: Update to use go-mod-bootstrap to fix issue with override un-done

RELEASE-NOTES.txt, internal/common/consts.go, pkg/service/main.go
=> fix: fix device service config stem in consul

README.md, RELEASE-NOTES.txt, api/oas3.0/v1/device-sdk.yaml, internal/common/consts.go, pkg/service/main.go
Fix #435 
pending on edgexfoundry/app-functions-sdk-go#356
=> feat: add ability for service name override

go.mod
Upgrade go-mod-core-contracts and go-mod-registry to the latest version
fix https://github.com/edgexfoundry/device-sdk-go/issues/524
Issue Number: #524
=> fix: Upgrade the Go modules to include the fixes

README.md, RELEASE-NOTES.txt, internal/common/consts.go, pkg/service/main.go
=> feat: replace --serviceName with --instance

internal/endpoint/endpoint.go
Signed-off-by: kaisawind <wind.kaisa@gmail.com>
- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Committing+Code+Guidelines#CommittingCodeGuidelines-CommitMessages
- [x ] Bugfix
Issue Number: #532
endpoint will fetch every 15s.
- [x ] No
Unknown
=> fix:device driver with consul takes so much cpu

README.md
Signed-off-by: charles-knox-intel <44684517+charles-knox-intel@users.noreply.github.com>
README.md has spelling and grammar mistakes. Some parts unclear for new readers. Could add extra context throughout the README to assist readers.
Issue Number: #537 
* Markdown linting passes
* Grammar and spelling issues fixed
* Updated verbiage and linkage throughout the document
No
N/A
=> docs(README.md): clarity for readers; fix #537

api/oas3.0/v2/device-sdk.yaml
=> Update API doc for query parameters

RELEASE-NOTES.txt
=> update RELEASE-NOTE for v1.2.3 release

internal/cache/profiles.go
SDK originally check CoreCommand first and return true if given command
exists, which might lead to some potential bug because Read/WriteCmd
functions are designed for DeviceCommand which rely on ResourceOperation
to access DeviceResource.
Update the CommandExists function to only check DeviceCommand to prevent
bugs addressed in #560 and rename the ResourceOperation map structure in
profile cache to be more specific.
fix #560 
=> fix: update CommandExists to only check Device Commands

example/cmd/device-simple/Dockerfile
Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Issue Number:
https://github.com/edgexfoundry/device-sdk-go/issues/569
=> refactor: update dockerfile to appropriately use ENTRYPOINT and CMD, closes#569

Dockerfile.build, Jenkinsfile, bin/test-attribution-txt.sh, example/cmd/device-simple/Dockerfile, go.mod, snap/snapcraft.yaml
update go.mod, Jenkinsfile, Dockerfile, Dockerfile.build, snapcraft.yml
and modify test-attribution-txt.sh to ignore explicit
fix #578
=> build: upgrade to use Go 1.15

Makefile, example/cmd/device-simple/Attribution.txt
update makefile to be consistent with edgex-go (add data race detector
for unit test) and remove unused attributions in Attribution.txt
fix #472
=> Update Makefile and clean attribution file

openapi/v2/device-sdk.yaml
Fix https://github.com/edgexfoundry/device-sdk-go/issues/555
1. add apiVersion to response schemas
2. correct ping, version, metric, config request methods
- [] Docs have been added / updated (for bug fixes / features)
Issue Number: #555 
1. add apiVersion to response schemas
2. correct ping, version, metric, config request methods
no
no
=> Update V2 swagger file to consist with edgex-go

example/cmd/device-simple/Attribution.txt, go.mod, internal/common/consts.go, internal/controller/restrouter.go, internal/mock/mock_deviceclient.go, internal/telemetry/linux_cpu.go, internal/telemetry/telemetry.go, internal/telemetry/unimplemented_cpu.go, internal/telemetry/windows_cpu.go, internal/transformer/transformresult.go, internal/v2/controller/http/common.go, internal/v2/controller/http/controller.go, pkg/service/manageddevices.go
for consistency across services, all implementation are all reference to
https://github.com/edgexfoundry/app-functions-sdk-go/tree/master/internal/v2
this PR need to be merged before other v2 API PRs so that the controller can be reused.
=> feat: implement Device SDK v2 common API

go.mod, internal/common/consts.go, internal/controller/restfuncs.go, internal/controller/restfuncs_test.go, internal/controller/restrouter.go, internal/controller/restrouter_test.go, internal/v2/controller/http/common.go, internal/v2/controller/http/controller.go, pkg/service/init.go, pkg/service/service.go
We pass dic to all the rest/http functions, but most of them don't need it.
Issue Number:
Fix https://github.com/edgexfoundry/device-sdk-go/issues/610
Fix https://github.com/edgexfoundry/device-sdk-go/issues/611
Move dic to the controller variable, so we don't need to pass it each
time.
Use the correlation id header key in go-mod-contracts.
=> refactor: Simplify controller signatures

Jenkinsfile
Fix https://github.com/edgexfoundry/device-sdk-go/issues/616
Add stage to Jenkins pipeline
Issue Number:
#616
Each .yaml file in openapi/v1 and openapi/v2 will be pushed to SwaggerHub
=> Add Publish Swagger Parameters to Jenkinsfile

internal/controller/restrouter.go, internal/v2/controller/http/discovery.go
=> feat: implement v2 discovery API

internal/common/consts.go, internal/common/utils.go, internal/controller/restrouter.go, internal/v2/application/command.go, internal/v2/controller/http/command.go, internal/v2/controller/http/controller.go, internal/v2/controller/http/discovery.go
note: while implementing I've encountered #89, might be a good timing to clean this old issue as well
=> feat: implement v2 command API

go.mod, internal/controller/restrouter.go, internal/v2/application/callback.go, internal/v2/cache/devices.go, internal/v2/controller/http/callback.go, internal/v2/controller/http/controller.go
=> feat: implement v2 callback api

internal/autoevent/executor.go, internal/common/utils.go
=> refactor: update LogLevel for pushing event to coredata

example/README.md, pkg/service/async_test.go
add unit tests for ProvisionWatcher filter logic as a baseline for
each scenario and update the README about the ProvisionWatcher.
=> test/docs(sdk): update README and add unit tests

internal/autoevent/executor.go, internal/autoevent/executor_test.go, internal/autoevent/manager.go
Autoevent executors are not actually being updated.
fix #681 
use pointer for the executors so they'll be correctly updated.
=> fix: use pointer on Executor to correctly update it

internal/autoevent/executor.go, internal/autoevent/manager.go, pkg/service/init.go
Signed-off-by: weichou <weichou1229@gmail.com>
Issue Number: #657 
Add buffer and initial with the AsyncBufferSize for handling the auto event.
=> feat: autoevent adds buffer for sending event to coredata

pkg/service/service.go
On startup, if a DeviceService instance is found on metadata, DS now
will update the instance to reflect current configuration.
SDK will do nothing if a matched DS is found on metadata during startup.
fix #572 
SDK will update the existed DS instance on metadata to reflect configuration change.
=> feat: update DS in metadata to reflect config change

RELEASE-NOTES.txt
=> docs: update release note for 1.4.0 release

Dockerfile.build, example/cmd/device-simple/Dockerfile
Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>
=> ci: standardize dockerfiles

internal/common/consts.go, internal/controller/restrouter.go, internal/v2/controller/http/callback.go, internal/v2/controller/http/command.go, internal/v2/controller/http/discovery.go, openapi/v2/device-sdk.yaml
fix #700
Use base response instead of nil and upgrade the go-mod-core-contract version
This PR should pending until https://github.com/edgexfoundry/go-mod-core-contracts/pull/405 reviewed and merged.
=> feat: Modify callback func to consist with V2 API

internal/v2/application/callback.go, internal/v2/cache/init.go, internal/v2/cache/provisionwatcher.go, internal/v2/controller/http/callback.go, openapi/v2/device-sdk.yaml
=> feat(v2): add v2 ProvisionWatcher cache and callback API

go.mod, internal/controller/restrouter.go, internal/v2/application/callback.go, internal/v2/application/command.go, internal/v2/controller/http/callback.go, openapi/v2/device-sdk.yaml
the v2 api definition and implementation are outdated, update it according to latest WG's discussion.
- remove GET/PUT `/device/{id}/{command}` route
- update DELETE callback to `/callback/xxx/name/{name}`
- remove POST `/callback/profile` and DELETE `/profile/id/{id}`
=> update device service v2 api per WG's discussion

openapi/v2/device-sdk.yaml
fix #752
The current swagger V2 doc doesn't sync with https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/device-service/0011-DeviceService-Rest-API.md#device, and needs to be updated.
=> [V2 API] Update swagger doc with updated Device Command API

internal/v2/cache/const_test.go, internal/v2/cache/devices.go, internal/v2/cache/devices_test.go, internal/v2/cache/profiles.go, internal/v2/cache/profiles_test.go, internal/v2/cache/provisionwatcher.go, internal/v2/cache/provisionwatcher_test.go
=> Remove id-name map in v2 cache

internal/v2/application/command.go, internal/v2/controller/http/command.go
=> refactor: replace PUT command wording to SET command

internal/controller/restrouter.go, pkg/service/async.go
AutoEVents will be fired automatically if specified in ProvisionWatcher
=> feat: spawn autoevents for discovered device

example/cmd/device-simple/res/configuration.toml, go.mod, internal/autoevent/executor.go, internal/autoevent/executor_test.go, internal/autoevent/manager.go, internal/clients/init.go, internal/clients/init_test.go, internal/common/consts.go, internal/transformer/transform.go, internal/v2/application/command.go, pkg/models/asyncvalues.go, pkg/models/commandvalue.go, pkg/models/commandvalue_test.go, pkg/service/async.go, pkg/service/managedautoevents.go
Close #803
Upgrade the go-mod-core-contracts lib
=> build: Upgrade the go-mod-core-contracts lib

pkg/service/async.go, pkg/service/async_test.go
=> refactor: fix problematic terminology in SDK

Dockerfile.build, Makefile, example/cmd/device-simple/Attribution.txt, example/cmd/device-simple/Dockerfile, example/cmd/device-simple/res/configuration.toml, go.mod, internal/application/command.go, internal/autoevent/executor.go, internal/clients/init.go, internal/clients/init_test.go, internal/common/utils.go, internal/config/config.go, internal/config/types.go, internal/container/client.go, internal/container/config.go, internal/controller/http/common_test.go, internal/provision/devices.go, pkg/service/async.go, pkg/service/main.go, pkg/service/service.go
Device Service will publish event to MessageBus if configured to do so.
~~The CI failure is because of the missing Attribution, will update it once all the discussion are finalized.~~
=> feat: add MessageBus capability

example/cmd/device-simple/Attribution.txt, example/cmd/device-simple/res/configuration.toml, go.mod, internal/config/types.go
Registry/Config access token not supported
Registry/Config access token now supported
=> feat: Enable Registry and Config access token

internal/application/command.go, internal/transformer/transform.go
remove the warning logging message when RO mapping not found.
=> refactor: remove RO mapping not found warning log 

example/cmd/device-simple/Attribution.txt, go.mod, internal/application/command.go, pkg/models/commandrequest.go
DeviceResource.Attributes is now `map[string]interface{}` type (https://github.com/edgexfoundry/go-mod-core-contracts/pull/594), update the corresponding part in SDK as well.
=> feat: update CommandRequest.Attributes type

go.mod, internal/controller/http/command.go, internal/controller/http/restrouter.go
binary reading (event) will be CBOR encoded instead of JSON encoded.
=> feat: CBOR encoding http response for binary reading

pkg/service/service.go
There are 2 issues in the original issue:
1. panic during `UpdateDeviceService` callback, because `DeviceService.deviceService` is assigned in the end of `selfRegister` method:
https://github.com/edgexfoundry/device-sdk-go/blob/92affc97e25621ac5a3617c0e5e42feb55191c77/pkg/service/service.go#L221
Also callback is asynchronously triggered by metadata, if the callback handler called before above line there will be panic.
Move the line in the beginning of `selfRegister` to fix this.
2. panic …
=> fix: correctly update DeviceService.deviceService model

Dockerfile.build, Makefile, example/cmd/device-simple/Dockerfile, go.mod, internal/controller/http/command.go, internal/provision/devices.go, internal/provision/profiles.go
=> build: upgrade Golang to 1.16

snap/snapcraft.yaml
=> build: update snap build to use Golang 1.16

example/cmd/device-simple/res/devices/simple-device.json.example, example/cmd/device-simple/res/devices/simple-device.toml, go.mod, internal/autoevent/executor.go, internal/autoevent/executor_test.go, pkg/service/managedautoevents.go
=> refactor: rename AutoEvent.Frequency field to Interval

snap/snapcraft.yaml
- update snap build to use go 1.16 via a build-snap
- update snap build to be consistent with other device services
=> build: update snap build

internal/controller/http/common.go, internal/controller/http/common_test.go
Add secret has obsolete code to ensure path has correct slashes.
Obsolete code removed.
=> refactor: Remove obsolete code from Add Secret

example/cmd/device-simple/res/profiles/Simple-Driver.json.example, internal/provision/profiles.go
=> feat: support device profile provision in json format

internal/clients/init.go
=> feat: remove coredata dependency

example/cmd/device-simple/res/configuration.toml
=> feat: Enable using MessageBus as the default

go.mod
Update Core Contracts lib to v2.0.0-dev.103
=> build: Update Core Contracts lib to v2.0.0-dev.103

go.mod
Signed-off-by: lenny <leonard.goodell@intel.com>
Use v2.0.0 tag which has cached issue of previous tagged commit.
Using v2.0.1 version
=> build: Update to go-mod-messaging v2.0.1

go.mod
Some go-mods still pre-release versions
All go-mods on released verions
=> build: Update remaining go-mods to released version

openapi/v2/device-sdk.yaml
Signed-off-by: Cherry Wang <cherry@iotechsys.com>
Closes #994
=> fix: Change V2 Swagger API version to 2.0.0

example/README.md, example/cmd/device-simple/res/provisionwatcher.json
=> docs: update device-simple README and provisionwatcher example

GOVERNANCE.md, OWNERS.md, example/cmd/device-simple/res/configuration.toml, example/cmd/device-simple/res/devices/simple-device.toml
also added governance.md and owner.md files for LF Edge
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
=> fix: update all TOML to use quote and not single-quote

example/cmd/device-simple/Dockerfile
Signed-off-by: jpwhitemn <jpwhite_mn@yahoo.com>
=> build: update alpine base to 3.14

internal/application/command.go
Closes: #1021
The error variable was redeclared in the case section, so the error checking didn't catch the error and throw the nil pointer result.
Remove the colon to avoid declaring the error variable again
=> fix: Fix nil pointer error when executing SET command with empty value

.github/Contributing.md
Updated PR template to latest approved template
=> ci: Update PR Template

example/cmd/device-simple/res/profiles/Simple-Driver.json.example, example/cmd/device-simple/res/profiles/Simple-Driver.yaml, example/driver/simpledriver.go, go.mod, internal/transformer/transform.go, pkg/models/commandvalue.go, pkg/models/commandvalue_test.go
Closes #1024
Added doc description to swagger API https://github.com/edgexfoundry/edgex-go/pull/3742
Handle the object value type for the event reading
=> feat: Support Object value type in Reading

pkg/models/commandvalue.go, pkg/models/commandvalue_test.go
=> feat: add NewCommandValueWithOrigin function

openapi/v2/device-sdk.yaml
=> docs: Update swagger version to 2.1.0

CHANGELOG.md
**N/A for change log**
**N/A for change log**
=> docs: Update Change Log for Jakarta

README.md
Replace the references of master with main branch
Upgrade the document links from v1.2 to v2.1
Fix the broken link refer to LTS Policy
Close https://github.com/edgexfoundry/device-sdk-go/issues/1059
=> docs: Correct document links in README (main branch)

openapi/v2/device-sdk.yaml
**N/A to swagger**
**N/A to swagger**
=> docs: Publish swagger to 2.2.0

internal/controller/http/validation.go, openapi/v2/device-sdk.yaml
pre-requisite of https://github.com/edgexfoundry/edgex-go/issues/3894
1. Run device-simple
2. Send a validation request to `/api/v2/validate/device`
3. check 200 response is a [BaseResponse](https://github.com/edgexfoundry/go-mod-core-contracts/blob/690068cdb04801aad11f6238554faec289449ce8/dtos/common/base.go#L32-L37)
=> fix: update validation API 200 response

internal/clients/init.go
Remove the core-data client when using the MessageBus before client bootstrapping
Closes #1157
- Build the device-virtaul-go image base on this change
- Deploy EdgeX without core-data
- Inspect the device-virtaul-go running successfully
=> fix: Remove core-data client when using the MessageBus

openapi/v2/device-sdk.yaml
=> docs: Publish swagger to 2.3.0

example/cmd/device-simple/res/configuration.toml
=> fix: update device-simple CommandRequestTopic config

example/cmd/device-simple/res/configuration.toml
=> fix: update example request/response topic scheme

internal/controller/messaging/command.go
=> fix: publish envelope with empty payload when ds-returnevent=no

openapi/v2/device-sdk.yaml
This PR updates the OpenAPI version yaml the next release version 2.4.0
=> ci: automated version changes for OpenAPI version: [2.4.0]

README.md, example/cmd/device-simple/Dockerfile, go.mod, go.sum, snap/snapcraft.yaml
BREAKING CHANGE: renamed -c/--confdir to -cd/--configDirand -f/--file to -cf/--configFile
https://github.com/edgexfoundry/edgex-docs/pull/916
1. build device-simple
2. run `device-simple  -h`
verify flags in help have new names
3. run `device-simple --confdir <path>`, `device-simple -c <path>`, `device-simple --file <file>` and `device-simple -f <file>`
verify errors that the flags are not defined
4. run `device-simple --configDir <path>`, `device-simple -cd <path>`, `device-simple …
=> refactor!: Rename command line flags for the sake of consistency

example/cmd/device-simple/res/configuration.toml, go.mod, go.sum, internal/application/callback.go, internal/controller/http/callback.go, internal/controller/http/restrouter.go, internal/controller/messaging/callback.go, openapi/v3/changes.txt, openapi/v3/device-sdk.yaml, pkg/service/main.go
BREAKING CHANGE: remove PUT /callback/profile  REST endpoint
1. build and run device-simple from this branch and core-metadata from https://github.com/edgexfoundry/edgex-go/pull/4343
2. update an associated device profile
3. received the system event from core metadata and update the profile successfully
The debug logs:
```
level=DEBUG ts=2023-02-10T10:27:27.511728235Z app=device-simple source=callback.go:56 msg="System event received on message queue. Topic: …
```
=> feat!: replace REST device profile callback with System Events

example/cmd/device-simple/res/configuration.toml
=> refactor: tweaks to private config

go.mod, go.sum, internal/controller/http/common.go, internal/controller/http/common_test.go
=> build(deps)!: Upgrade contracts mod to update /secret DTO

go.mod, go.sum, internal/application/command.go, internal/common/utils.go, internal/config/types.go, openapi/v3/device-sdk.yaml
BREAKING CHANGE: Remove LastConnected, LastReported and UpdateLastConnected configs
https://github.com/edgexfoundry/edgex-docs/pull/965
=> feat!: Remove LastConnected, LastReported and UpdateLastConnected configs

internal/application/callback.go
close #1347
1. build device-virtual from https://github.com/edgexfoundry/device-virtual-go/pull/347 based on this branch
2. create a new device resource
```
curl -ki -X POST http://localhost:59881/api/v2/deviceprofile/resource -d '[  
{
"apiVersion": "v2","profileName":"Random-Boolean-Device",
"resource": {
"name": "resource-add-1", 
"properties": {"valueType": "Bool","readWrite": "RW"}}
}
]'
```
3. Send GET command to read the new device resource successfully
```
curl -ki …
```
=> fix: Add UpdateDevice callback for device profile update

internal/controller/http/restrouter.go
BREAKING CHANGE: Incoming REST API calls must have a JWT authentication token, with the exception
of /api/v2/ping.
This change is related to the implementation of the microservice authentication (token-based) ADR.
This commit also consumes the breaking interface change to go-mod-core-contracts.
As a library, there is no way to directly test the effect of this change, other than "make test",
until it is integrated into downstream device clients.
=> feat!: Apply JWT authentication to incoming calls

Jenkinsfile
=> build: [Levski] Set go version to 1.18 in Jenkinsfile

Makefile, example/cmd/device-simple/Dockerfile, go.mod, internal/autoevent/executor_test.go, pkg/models/commandvalue_test.go
Run non-secure EdgeX stack
Build and run Device Simple from command line
Verify logs shows autoevents being published
=> build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

CHANGELOG.md
=> docs: Levski change log updated

go.mod, go.sum
=> build: Update to latest modules w/o TOML package

example/cmd/device-simple/res/provisionwatchers/Simple-Provision-Watcher.json.example, example/cmd/device-simple/res/provisionwatchers/Simple-Provision-Watcher.yml, go.mod, go.sum, internal/application/callback.go, pkg/service/async.go, pkg/service/managedwatchers.go
Apply provision watcher model changes and skip the locked provision watcher.
Implementation based on the core-contracts PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/820
- Run core service, and device service and enable the discovery
- Send discovery API and check the discovered device is added to the metadata service
=> feat!: Apply provision watcher model changes

.github/dependabot.yml
=> build: Ignore all go-mods except go-mod-bootstrap

internal/cache/init.go, internal/common/utils_test.go, internal/controller/http/command_test.go, internal/controller/messaging/callback.go, internal/provision/devices.go, internal/transformer/transform_test.go, pkg/service/async.go, pkg/service/init.go, pkg/service/service.go
=> feat: Enhance autodiscovery to better support  multiple instances of same device service

CHANGELOG.md
=> docs: Update chnagelog for 3.0

internal/provision/uri-test-files/README.md, internal/provision/uri-test-files/devices/index.json, internal/provision/uri-test-files/devices/simple-device.yml, internal/provision/uri-test-files/devices/simple-device2.yaml, internal/provision/uri-test-files/profiles/Simple-Driver.yaml, internal/provision/uri-test-files/profiles/Simple-Driver2.yml, internal/provision/uri-test-files/profiles/index.json, internal/provision/uri-test-files/provisionwatchers/Simple-Provision-Watcher.yml, internal/provision/uri-test-files/provisionwatchers/Simple-Provision-Watcher2.yaml, internal/provision/uri-test-files/provisionwatchers/index.json
=> test: Add URI test files

pkg/interfaces/service.go, pkg/service/service.go
Closes #1474
No existing test suite to test this code, however, it is similar to the app-service-sdk-go change and should function identically.
=> feat(security): New AddCustomRoute method with authentication parameter

Makefile, example/cmd/device-simple/Dockerfile, go.mod
make test
make build
make docker
Verify all are successful
=> build: Upgrade to go-1.21, Linter1.54.2 and Alpine 3.18

internal/controller/http/restrouter.go
=> refactor: Remove the version number in Init logs

example/cmd/device-simple/Dockerfile
=> fix: Address CVE in Alpine base image

go.mod, go.sum, internal/application/callback.go, internal/application/command.go, openapi/v3/device-sdk.yaml
refer to https://github.com/edgexfoundry/go-mod-core-contracts/issues/901
=> feat: Allow empty profileName in Device

example/cmd/device-simple/Attribution.txt, internal/cache/init.go
Close https://github.com/edgexfoundry/device-sdk-go/issues/1604
=> fix: Cache init should ignore empty profile

internal/application/profilescan.go, internal/controller/http/discovery.go, openapi/v3/device-sdk.yaml
Added more logging and return base response to autodiscovery as well Close https://github.com/edgexfoundry/device-sdk-go/issues/1606
=> fix: Correct ProfileScan err handling and response

example/README.md, internal/application/callback.go, internal/controller/messaging/callback.go
=> fix: Remove device profile from the cache properly

internal/application/command.go
=> fix: Change status code to 400 for write commands with invalid values

.golangci.yml, Makefile, example/cmd/device-simple/Dockerfile, go.mod, go.sum
=> build: Upgrade to go-1.23, Linter1.61.0 and Alpine 3.20

example/cmd/device-simple/Attribution.txt, go.mod, go.sum, internal/autoevent/executor_test.go
Allow store reading value as null
=> feat: Allow store reading value as null

go.mod, go.sum
=> build: update to bootstrap 4.0.2

openapi/device-sdk.yaml
=> docs: Add missing ObjectReading in Event Readings schema

openapi/device-sdk.yaml
=> docs: Add missing jsonObject param in GET /device/name/{name}/{command}
